#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=68:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=12

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=85500mb

#PBS -N aaalignreads-trinityStyle
##PBS -q bigiron


#Number of times to run this script
#PBS -t 1-21

set eu
umask 007

##home=/gpfs/fs3/home/rreid2
#cd $HOME/blueberry/reads/illumina/091230Sequence1/
#export PATH=/sw/bowtie/bin/:$HOME/bin/sopra/source_codes_v1.4.3/SOPRA_with_prebuilt_contigs:$PATH
#file=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/p2ep/oat/badassay/fastq/file.txt)
file=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/p2ep/blueberry/rnaseq/sra-srr118/gage/file.txt)


module load bwa

cd /lustre/groups/p2ep/blueberry/rnaseq/sra-srr118/gage/alignreads

#create index of reference
#bwa index -p ${file}.idx -a bwtsw /group/p2ep/blueberry/rnaseq/sra-srr118/cdhit/${file}-cdhit

module load htslib/1.1-1
module load samtools
################   Success was part below #####
#################################################		Removed the -I from bwa aln and this solves the alingment issue (casava 1.3+  vs 1.5+   #############


bwa index -p ${file}.idx -a bwtsw /group/p2ep/blueberry/rnaseq/sra-srr118/cdhit/${file}-cdhit
bwa aln  -t 12 ${file}.idx  /group/p2ep/blueberry/rnaseq/sra-srr118/fastx/${file}_fastx-trim.fq  > ${file}.aln.sai
samtools view -bS ${file}.sam | samtools sort - ${file}-sort




~/sw/trinityrnaseq_r2013-02-25/util/alignReads.pl \
 --single  /group/p2ep/blueberry/rnaseq/sra-srr118/fastx/${file}_fastx-trim.fq  \
 --seqType fq \
--target /group/p2ep/blueberry/rnaseq/sra-srr118/cdhit/${file}-cdhit \
 --aligner bwa \
--retain_intermediate_files \
--retain_SAM_files \
-- -t 12 \
--output ${file}-bwa 
 cd ${file}-bwa; \

~/sw/trinityrnaseq_r2013-02-25/util/SAM_nameSorted_to_uniq_count_stats.pl ${file}-bwa.nameSorted.sam > ../qc-${file}.txt 
 samtools idxstats ${file}-bwa.coordSorted.bam > ../readspercontig-${file}.txt

#samtools import /lustre/groups/p2ep/blueberry/genomic/newblerAssembly.fna Fla4BxW85-385vsnewbler.sam  Fla4BxW85-385vsnewbler.bam

#samtools view -bS ${file}.sam | samtools sort - ${file}-sort

#samtools index ${file}-sort.bam

#samtools mpileup -ugf /lustre/groups/p2ep/oat/badassay/WG00014_OAT.targetSeq.fa ${file}-sort.bam | bcftools view -bvcg - > ${file}.bcf
#bcftools view ${file}.bcf > ${file}.vcf 

 
