#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=196:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=1

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
##PBS -l pmem=7600mb
#PBS -l vmem=79gb
#PBS -N Ilovethisbarrrr
##PBS -q bigiron
#export TMPDIR=$HOME/tmp

#Number of times to run this script
##PBS -t 1-12


cd ~/p2ep/

#file=$(sed -n -e "${PBS_ARRAYID}p" files.txt)
i=3
#barcodes=broccoxBNC
#barcodes=DraperJewel
barcodes=Fla4BxW85
#echo   ${file};

#module load fastx-toolkit/0.0.13.2

#####    5      #####
#gunzip /lustre/groups/bioservices/p2ep/fromJessePoland/188.180.77.18/A2094_FastQ/Sample_GBS0381_38${i}/GBS0381_38${i}_NoIndex_L00${i}_R1_001.fastq.gz
#cat /lustre/groups/bioservices/p2ep/fromJessePoland/188.180.77.18/A2094_FastQ/Sample_GBS0381_38${i}/GBS0381_38${i}_NoIndex_L00${i}_R1_001.fastq | ~/scripts/perl/fastx_barcode_splitter.pl --bcfile Fla4BxW85-barcodes-lane5.txt --bol --mismatches 0 \
#	--prefix ~/p2ep//Fla4BxW85_${i}_ --suffix ".fna"

######  3    #######
#gunzip /lustre/groups/bioservices/p2ep/fromJessePoland/188.180.77.18/A2094_FastQ/Sample_GBS0381_383/GBS0381_383_NoIndex_L003_R1_001.fastq.gz
#cat /lustre/groups/bioservices/p2ep/fromJessePoland/188.180.77.18/A2094_FastQ/Sample_GBS0381_383/GBS0381_383_NoIndex_L003_R1_001.fastq | ~/scripts/perl/fastx_barcode_splitter.pl --bcfile Fla4BxW85-barcodes-lane${i}.txt --bol --mismatches 0 \
#        --prefix ~/p2ep//Fla4BxW85_${i}_ --suffix ".fna"


#####    4      #####
#gunzip /lustre/groups/bioservices/p2ep/fromJessePoland/188.180.77.18/A2094_FastQ/Sample_GBS0381_38${i}/GBS0381_38${i}_NoIndex_L00${i}_R1_001.fastq.gz
cat /lustre/groups/bioservices/p2ep/fromJessePoland/188.180.77.18/A2094_FastQ/Sample_GBS0381_38${i}/GBS0381_38${i}_NoIndex_L00${i}_R1_001.fastq | ~/scripts/perl/fastx_barcode_splitter.pl --bcfile ${barcodes}-barcodes-lane${i}.txt --bol --mismatches 0 \
         --prefix ~/p2ep//${barcodes}_${i}_ --suffix ".fastq"



echo "finished job"

