#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=68:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=12

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=85500mb

#PBS -N geeeeeeBS-bowtie 
##PBS -q bigiron


#Number of times to run this script
#PBS -t 1-79

set eu
umask 007

##home=/gpfs/fs3/home/rreid2
#cd $HOME/blueberry/reads/illumina/091230Sequence1/
file=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/p2ep/GBS_data/barcodeSplit/Fla4BxW85/goodfiles.txt)

module load bowtie

cd /lustre/groups/p2ep/GBS_data/bowtie/bb-78progeny

#create index of reference
#bowtie-build /lustre/groups/p2ep/GBS_data/barcodeSplit/Fla4BxW85/good/all-reads.fastq ./allreads

bowtie -S -q -p 12 ./allreads /lustre/groups/p2ep/GBS_data/barcodeSplit/Fla4BxW85/good/${file}.fastq ${file}.sam

module load samtools

################   Success was part below #####
#################################################		Removed the -I from bwa aln and this solves the alingment issue (casava 1.3+  vs 1.5+   #############
#bwa aln  -t 12 NEWBLER.idx /lustre/groups/p2ep/GBS_data/barcodeSplit/Fla4BxW85/good/${file}.fastq > ${file}.aln.sai
#bwa samse NEWBLER.idx ${file}.aln.sai /lustre/groups/p2ep/GBS_data/barcodeSplit/Fla4BxW85/good/${file}.fastq  >  ${file}.sam

#samtools import /lustre/groups/p2ep/blueberry/genomic/newblerAssembly.fna Fla4BxW85-385vsnewbler.sam  Fla4BxW85-385vsnewbler.bam

#samtools view -F 0x04 -b Fla4BxW85-385vsnewbler.bam > Fla4BxW85-385vsnewbler.rmd.bam
#samtools sort Fla4BxW85-385vsnewbler.rmd.bam  Fla4BxW85-385vsnewbler.rmd.bam.srt
samtools view -bS ${file}.sam | samtools sort - ${file}-sort

#samtools index ${file}-sort.bam

samtools mpileup -ugf /lustre/groups/p2ep/GBS_data/barcodeSplit/Fla4BxW85/good/${file}.fastq ${file}-sort.bam | bcftools view -bvcg - > ${file}.bcf
bcftools view ${file}.bcf > ${file}.vcf 

#samtools view -F 0x04 -b Fla4BxW85-383vsnewbler.bam > Fla4BxW85-383vsnewbler.rmd.bam
#samtools sort Fla4BxW85-383vsnewbler.rmd.bam  Fla4BxW85-383vsnewbler.rmd.bam.srt
#samtools index Fla4BxW85-383vsnewbler.rmd.bam.srt.bam
 
