#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=68:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=6

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=75500mb

#PBS -N Kaaahhhhhhn 
##PBS -q bigiron


#Number of times to run this script
##PBS -t 1-2

set eu
umask 007

##home=/gpfs/fs3/home/rreid2
#cd $HOME/blueberry/reads/illumina/091230Sequence1/
#export PATH=/sw/bowtie/bin/:$HOME/bin/sopra/source_codes_v1.4.3/SOPRA_with_prebuilt_contigs:$PATH
#ssid=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/bioservices/secure/kohlmeier/5kregion/filtered/file7-14.txt)

module load bwa

cd /lustre/groups/p2ep/GBS_data/bwa/

#create index of reference
bwa index -p MIRA.idx -a bwtsw /lustre/groups/p2ep/blueberry/genomic/miraAssembly.fna

module load samtools

################   Success was part below #####
#################################################		Removed the -I from bwa aln and this solves the alingment issue (casava 1.3+  vs 1.5+   #############
bwa aln  -t 12 MIRA.idx /lustre/groups/p2ep/GBS_data/fromJessePoland/sftp_upload/GBS0385xFla4BxW85_C2AT0ACXX_s_5_fastq > Fla4BxW85-385.aln.sai
bwa aln  -t 12 MIRA.idx /lustre/groups/p2ep/GBS_data/fromJessePoland/sftp_upload/GBS0383xFla4BxW85_C2AT0ACXX_s_3_fastq > Fla4BxW85-383.aln.sai
bwa samse MIRA.idx Fla4BxW85-385.aln.sai /lustre/groups/p2ep/GBS_data/fromJessePoland/sftp_upload/GBS0385xFla4BxW85_C2AT0ACXX_s_5_fastq  >  Fla4BxW85-385vsmira.sam
bwa samse MIRA.idx Fla4BxW85-383.aln.sai /lustre/groups/p2ep/GBS_data/fromJessePoland/sftp_upload/GBS0383xFla4BxW85_C2AT0ACXX_s_3_fastq  >  Fla4BxW85-383vsmira.sam

samtools import /lustre/groups/p2ep/blueberry/genomic/miraAssembly.fna Fla4BxW85-385vsmira.sam  Fla4BxW85-385vsmira.bam
samtools import /lustre/groups/p2ep/blueberry/genomic/miraAssembly.fna Fla4BxW85-383vsmira.sam  Fla4BxW85-383vsmira.bam

samtools view -F 0x04 -b Fla4BxW85-385vsmira.bam > Fla4BxW85-385vsmira.rmd.bam
samtools sort Fla4BxW85-385vsmira.rmd.bam  Fla4BxW85-385vsmira.rmd.bam.srt
samtools index Fla4BxW85-385vsmira.rmd.bam.srt.bam

samtools mpileup -ugf /lustre/groups/p2ep/blueberry/genomic/miraAssembly.fna Fla4BxW85-385vsmira.rmd.bam.srt.bam | bcftools view -bvcg - > Fla4BxW85-385vsmira.bcf
bcftools view Fla4BxW85-385vsmira.bcf > Fla4BxW85-385vsmira.vcf 

samtools view -F 0x04 -b Fla4BxW85-383vsmira.bam > Fla4BxW85-383vsmira.rmd.bam
samtools sort Fla4BxW85-383vsmira.rmd.bam  Fla4BxW85-383vsmira.rmd.bam.srt
samtools index Fla4BxW85-383vsmira.rmd.bam.srt.bam
 
samtools mpileup -ugf /lustre/groups/p2ep/blueberry/genomic/miraAssembly.fna Fla4BxW85-383vsmira.rmd.bam.srt.bam | bcftools view -bvcg - > Fla4BxW85-383vsmira.bcf
bcftools view Fla4BxW85-383vsmira.bcf > Fla4BxW85-383vsmira.vcf
