#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=168:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=12

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=92gb
##PBS -l vmem=400gb

#PBS -N seedeeHITs-bbts
##PBS -q bigiron

#Number of times to run this script
##PBS -t 1-21

set eu
umask 007

#file=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/p2ep/blueberry/rnaseq/sra-srr118/fileHiseq.txt)
#file=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/lorainelab/data/illumina/sweet_potato/filtered/concat/file.txt)

module load bowtie
#module load oases

cd /lustre/groups/p2ep/blueberry/rnaseq/sra-srr118/cdhit
echo `pwd`

#perl ~/sw/trinityrnaseq_r2013-02-25/Trinity.pl --seqType fq --JM 400G --output V012-trinity \
# --left /lustre/groups/p2ep/rnaseq/raw/merge-V012_CTTGTA_L002_R1.fastq \
# --right /lustre/groups/p2ep/rnaseq/raw/merge-V012_CTTGTA_L002_R2.fastq --CPU 8

#perl ~/sw/trinityrnaseq_r2013-02-25/Trinity.pl --seqType fq --JM 400G --output ${file}-trinity \
# --single /lustre/groups/p2ep/blueberry/rnaseq/sra-srr118/fastx/${file}_fastx-trim.fq  --CPU 8


module load ncbi-blast+

#cat ../finalTri-*.fna > all21Assemblies.fna
#cp ../trinity/${file}-trinity/Trinity.fasta ../finalTri-${file}.fna
/home/rreid2/sw/cd-hit-v4.6.1-2012-08-27/cd-hit -i all21Assemblies.fna -T 24 -M 0 -o 21all-cdhit-2
