#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=68:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=12

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=85500mb

#PBS -N ccc-cegma 
#PBS -q bigiron


#Number of times to run this script
##PBS -t 1-228

set eu
umask 007

##home=/gpfs/fs3/home/rreid2
#cd $HOME/blueberry/reads/illumina/091230Sequence1/
#export PATH=/sw/bowtie/bin/:$HOME/bin/sopra/source_codes_v1.4.3/SOPRA_with_prebuilt_contigs:$PATH
#file=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/p2ep/oat/badassay/fastq/file.txt)

module load blat

cd /lustre/groups/p2ep/blueberry/cegma/

cegma -g ~/sw/cegma/CEGMA_v2.5/sample/sample.dna -p ~/sw/cegma/CEGMA_v2.5/sample/sample.prot  --output testsample
cegma --genome /lustre/groups/p2ep/blueberry/genomic/sspace-take6.fna \
 --output cegma-garm-default \
--threads 12 \
-p ~/sw/cegma/CEGMA_v2.5/data/A.thaliana.aa

cegma --genome /lustre/groups/p2ep/blueberry/genomic/sspace-take6.fna \
 --output cegma-finisher-default \
 --threads 12 \
-p ~/sw/cegma/CEGMA_v2.5/data/A.thaliana.aa

#create index of reference
#blat -minIdentity=92 -t=dna -q=dna /lustre/groups/p2ep/blueberry/garm/mas2newb/bothScafBin.fna  bot1.fna   blat-bb-pot2garm.psl
#~/scripts/perl/blat2gff.pl < blat-bb-pot2garm.psl > blat-bb-pot2garm.gff

#bwa index -p SASKREF.idx -a bwtsw /lustre/groups/p2ep/brassica/Boleracea.v1.pep.fasta

echo "Fin"
#module load samtools
#file=bwa-brass-scaff
################   Success was part below #####
#################################################		Removed the -I from bwa aln and this solves the alingment issue (casava 1.3+  vs 1.5+   #############
#bwa aln  -t 12 SASKREF.idx /lustre/groups/p2ep/brassica/masurca-v158/CA/10-gapclose/genome.scf.fasta > ${file}.aln.sai
#bwa mem -t 12 SASKREF.idx /lustre/groups/p2ep/brassica/masurca-v158/CA/10-gapclose/genome.scf.fasta  >  ${file}.sam

#samtools import /lustre/groups/p2ep/blueberry/genomic/newblerAssembly.fna Fla4BxW85-385vsnewbler.sam  Fla4BxW85-385vsnewbler.bam

#samtools view -F 0x04 -b Fla4BxW85-385vsnewbler.bam > Fla4BxW85-385vsnewbler.rmd.bam
#samtools sort Fla4BxW85-385vsnewbler.rmd.bam  Fla4BxW85-385vsnewbler.rmd.bam.srt
#samtools view -bS ${file}.sam | samtools sort - ${file}-sort

#samtools index ${file}-sort.bam

#samtools mpileup -ugf /lustre/groups/p2ep/oat/badassay/WG00014_OAT.targetSeq.fa ${file}-sort.bam | bcftools view -bvcg - > ${file}.bcf
#bcftools view ${file}.bcf > ${file}.vcf 

 
