#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=68:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=12

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=15500mb

#PBS -N ccconverted2commas  
##PBS -q bigiron


#Number of times to run this script
##PBS -t 1-18

##home=/gpfs/fs3/home/rreid2
#cd $HOME/blueberry/reads/illumina/091230Sequence1/
#ssid=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/janieslab/contigs-trinity/files.txt)


cd /lustre/groups/bioservices/p2ep/brassica/orthocluster/ 

/lustre/home/rreid2/sw/orthov2.0/orthomclSoftware-v2.0.3/bin/orthomclBlastParser   ./splitty/allvsall-blastp-format0.txt ./splitty/ind >> out.blastp.pbo 




