#!/bin/bash
# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=380:30:00


# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=12

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=90gb

#PBS -N cccorectDaSoap 
##PBS -q bigiron
#Number of times to run this script
##PBS -t 1-17
##PBS -t 12-22

set -eu
umask 007


#file=$(sed -n -e "${PBS_ARRAYID}p"  /lustre/groups/bioservices/p2ep/dhmri/run4-Duke-Jan2-2014/Project_UNCC_930_131213A1/file.txt)
#file2=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/bioservices/p2ep/dhmri/run3-nov25-13/fileheader.txt)
#sed -i.orig 's/^$/N/' /lustre/groups/bioservices/p2ep/dhmri/run2-oat-brass-oct25-2013/${file}_R1_001.cutadapt.fastq
#sed -i.orig 's/^$/N/' /lustre/groups/bioservices/p2ep/dhmri/run2-oat-brass-oct25-2013/${file}_R2_001.cutadapt.fastq

#mkdir /lustre/groups/p2ep/masurca/round3/$file
#cd ~/p2ep/masurca/UNCC_Schlueter_130909HiSeq_Run_Sample_3_059_AGTCAA_L003
#rm -r ~/p2ep/masurca/$file/*
cd /lustre/groups/p2ep/brassica/soap-v158/
#mkdir ${file}
#cd ${file}
#cp ../config-run3.txt ./

#sed -i.orig -e "s/foo/${file}/g" config-run3.txt
#perl /lustre/home/rreid2/sw/MaSuRCA-2.3.2/bin/runSRCA.pl config.txt
#./assemble.sh

#module load soapdenovo2/2.04-r240

cd nexABC

#/home/rreid2/sw/SOAPec_v2.01/bin/KmerFreq_AR  -k 23 -q 33 -t 12  -p test readlist.txt
#/home/rreid2/sw/SOAPec_v2.01/bin/Corrector_AR -k 23 -l 3 -L 3 -r 50 -t 10  test.freq.cz test.freq.cz.len readlist.txt >corr.log 2>corr.err

cd ../v158
/home/rreid2/sw/SOAPec_v2.01/bin/KmerFreq_AR  -k 17 -q 33 -t 12  -p test readlist.txt
 /home/rreid2/sw/SOAPec_v2.01/bin/Corrector_AR -k 17 -l 3 -L 3 -r 50 -t 10  test.freq.cz test.freq.cz.len readlist.txt >corr.log 2>corr.err
cd ../v158clean
/home/rreid2/sw/SOAPec_v2.01/bin/KmerFreq_AR  -k 17 -q 33 -t 12  -p test readlist.txt
 /home/rreid2/sw/SOAPec_v2.01/bin/Corrector_AR -k 17 -l 3 -L 3 -r 50 -t 10  test.freq.cz test.freq.cz.len readlist.txt >corr.log 2>corr.err
cd ../nexD
/home/rreid2/sw/SOAPec_v2.01/bin/KmerFreq_AR  -k 17 -q 33 -t 12  -p test readlist.txt
 /home/rreid2/sw/SOAPec_v2.01/bin/Corrector_AR -k 17 -l 3 -L 3 -r 50 -t 10  test.freq.cz test.freq.cz.len readlist.txt >corr.log 2>corr.err

echo -n 'All done ';date;
