#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=368:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=12

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=88gb
#PBS -q bigiron
#PBS -N eeexoner8-cegma2stuff

##PBS -t 1-5
umask 007
set -eu

#ssid=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/bioservices/hockeypuck/old/blueberry/reads/hiseq/file.txt)
#dir=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/bioservices/p2ep/dhmri/run2-oat-brass-oct25-2013/filedir.txt)

echo "Launching fastx"

#cd $home
module load exonerate
#mkdir /lustre/groups/p2ep/blueberry/markers/exonerate
cd /lustre/groups/p2ep/blueberry/cegma/exonerate/


######## SUCCESSSS  GARM   #######
#exonerate --querytype protein --targettype dna --model protein2genome --percent 90  ~/sw/cegma/CEGMA_v2.5/data/A.thaliana.aa ../../garm/mas2newb/bothScafBin.fna  > arabid458AA2garm-exo90.txt

#exonerate --querytype protein --targettype dna --model protein2genome --percent 50  ~/sw/cegma/CEGMA_v2.5/data/A.thaliana.aa ../../garm/mas2newb/bothScafBin.fna > arabid458AA2garm-exo50.txt


### Newbler  ###
#exonerate --querytype protein --targettype dna --model protein2genome --percent 90  ~/sw/cegma/CEGMA_v2.5/data/A.thaliana.aa ../../genomic/newblerAssembly.fna  > arabid458AA2newbler-exo90.txt

#exonerate --querytype protein --targettype dna --model protein2genome --percent 50  ~/sw/cegma/CEGMA_v2.5/data/A.thaliana.aa ../../genomic/newblerAssembly.fna > arabid458AA2newbler-exo50.txt


###  Nextera   ###
#exonerate --querytype protein --targettype dna --model protein2genome --percent 90  ~/sw/cegma/CEGMA_v2.5/data/A.thaliana.aa ../../genomic/masurca-nextera454.fna > arabid458AA2nextera-exo90.txt

#exonerate --querytype protein --targettype dna --model protein2genome --percent 50  ~/sw/cegma/CEGMA_v2.5/data/A.thaliana.aa ../../genomic/masurca-nextera454.fna > arabid458AA2nextera-exo50.txt

###    Take6    ###
exonerate --querytype protein --targettype dna --model protein2genome --percent 90  ~/sw/cegma/CEGMA_v2.5/data/A.thaliana.aa ../../genomic/sspace-take6.fna > arabid458AA2take6-exo90.txt

exonerate --querytype protein --targettype dna --model protein2genome --percent 50  ~/sw/cegma/CEGMA_v2.5/data/A.thaliana.aa ../../genomic/sspace-take6.fna > arabid458AA2take6-exo50.txt
