#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=168:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=24

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=488gb
#PBS -q bigiron
#PBS -N fffgene-take6

##PBS -t 1-5
umask 007
set -eu

#ssid=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/bioservices/hockeypuck/old/blueberry/reads/hiseq/file.txt)
#dir=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/bioservices/p2ep/dhmri/run2-oat-brass-oct25-2013/filedir.txt)

echo "Launching fgene"

#cd $home
#module load exonerate
#mkdir /lustre/groups/p2ep/blueberry/markers/exonerate
cd /lustre/groups/p2ep/blueberry/annot/take6/fgene/

export gf_data='/group/p2ep/blueberry/genomic/'  

~/sw/fgenes/lin/fgenes  "/group/p2ep/blueberry/genomic/masked-take6.fna" "resultWithQuotes.txt"
~/sw/fgenes/lin/fgenes  /group/p2ep/blueberry/genomic/masked-take6.fna resultWithQuotes.txt

