#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=168:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=24

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=388gb
#PBS -q bigiron
#PBS -N mmmergeViaGAA-bb

##PBS -t 1-5
umask 007
set -eu

#ssid=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/bioservices/hockeypuck/old/blueberry/reads/hiseq/file.txt)
#dir=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/bioservices/p2ep/dhmri/run2-oat-brass-oct25-2013/filedir.txt)

echo "Launching fastx"

#cd $home
module load blat

cd /lustre/groups/p2ep/blueberry/gaa/

blat /lustre/groups/p2ep/blueberry/genomic/newblerAssembly.fna  masurca-nextera.fna query_vs_target.psl
perl ~/gaa/gaa.pl --target /lustre/groups/p2ep/blueberry/genomic/newblerAssembly.fna   --query masurca-nextera.fna  --match query_vs_target.psl --output-dir mas2newb

#blat -minIdentity=92  /lustre/groups/p2ep/brassica/annot/referenceGenome/boleracea.v1.genome.fasta /lustre/groups/p2ep/brassica/ncbi-est-brass.fna  blat-brass-est2ref.psl

#~/scripts/perl/blat2gff.pl < blat-brass-est2ref.psl > blat-brass-est2ref.gff



echo "FIN"


