#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=168:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=24

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=480GB

#PBS -N fffallIntoThegap 
#PBS -q bigiron


#Number of times to run this script
##PBS -t 1-10
##PBS -l pmem=7600mb

set eu
umask 007

cd /lustre/groups/p2ep/blueberry/bac/gapfiller/
#module load bwa
module load samtools/0.1.19
#1st try

#perl /home/rreid2/sw/sspace/GapFiller_v1-10_linux-x86_64/GapFiller.pl -l libraries2.txt -s /lustre/groups/p2ep/blueberry/bac/sspace/take6/sspace-454bit.final.scaffolds.fasta -m 20 -o 2 -r 0.7 -n 10 -d 50 -t 10 -g 2 -T 24 -i 5 -b gap-take2

perl /home/rreid2/sw/sspace/GapFiller_v1-10_linux-x86_64/GapFiller.pl -l libraries3.txt -s /lustre/groups/p2ep/blueberry/bac/sspace/take6/sspace-454bit.final.scaffolds.fasta -m 20 -o 2 -r 0.7 -n 10 -d 50 -t 10 -g 2 -T 24 -i 5 -b gap-take3

echo "FIN"

#done
