#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=168:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=12

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=88gb
#PBS -q bigiron
#PBS -N gggenomethread-AOP

##PBS -t 1-5
umask 007
set -eu

#ssid=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/bioservices/hockeypuck/old/blueberry/reads/hiseq/file.txt)
#dir=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/bioservices/p2ep/dhmri/run2-oat-brass-oct25-2013/filedir.txt)

echo "Launching fastx"

#cd $home
#module load augustus
#module load blat

cd /lustre/groups/p2ep/brassica/glucosil/aop/

for i in 2 3
do

~/sw/genomethreader/gth-1.6.2-Linux_x86_64-64bit/bin/gth \
-species arabidopsis \
-cdna /lustre/groups/p2ep/brassica/glucosil/aop/AOP${i}.fasta \
-genomic /lustre/groups/p2ep/brassica/Boleracea.v1.genome.fasta \

done
echo "FIN"


