#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=296:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=1

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=7g

#PBS -N iiinterproExonr8
##PBS -q bigiron


#Number of times to run this script
#PBS -t 1-29

cd /lustre/groups/p2ep/blueberry/markers/2genesNearby/interpro/ 

file=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/p2ep/blueberry/markers/2genesNearby/splitty/file.txt)
#module load iprscan
#module load samtools

#echo "We are in a split ${ssid}"

#for i in 0 1 2 3 4 ; do
echo ${file}
#mkdir ${file}
#cd ${file}
#mkdir splitty
#cp ../aa/${file}/best_candidates.eclipsed_orfs_removed.pep ${file}.faa
#cd splitty
##python /home/rreid2/scripts/python/oneline.py ../../../aa/${file}/best_candidates.eclipsed_orfs_removed.pep >tmp.faa
##split -l 1000 ./tmp.faa bbts
#rm *-iprscan.out

#for f in bbts*
#do

sed s/\*// /group/p2ep/blueberry/markers/2genesNearby/individual-AA/${file}/best_candidates.eclipsed_orfs_removed.pep > /group/p2ep/blueberry/markers/2genesNearby/individual-AA/${file}/${file}-nostar.faa
~/sw/interproscan-5.7-48.0/interproscan.sh -i /group/p2ep/blueberry/markers/2genesNearby/individual-AA/${file}/${file}-nostar.faa -o ${file}-iprscan.out  -goterms -iprlookup -seqtype p -pa -appl Panther-9.0,PfamA-27.0,PrositeProfiles-20.97 -f tsv

#done

#cat *-iprscan.out > ../../all-${file}-iprscan.out


#~/sw/interproscan-5.7-48.0/interproscan.sh -cli -i ./all1-48.fasta${file}.faa -o ${file}.iprscan.out \
#	-format raw \
#	-pa \
#	-goterms -iprlookup \
#	-seqtype p \
#	-appl hmmpanther hmmpfam superfamily
#	-appl profilescan \
#	-appl hmmpfam \
#	-appl superfamily
#done


#module load iprscan
#iprscan -cli -i ./${ssid}.fna -o ${ssid}.iprscan.out -format raw -goterms -iprlookup

echo `pwd`

