#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=296:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=1

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=7g

#PBS -N iiinterproCran
##PBS -q bigiron


#Number of times to run this script
#PBS -t 1-294

cd /lustre/groups/p2ep/blueberry/cran/aa/splitty/ 

file=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/p2ep/blueberry/cran/aa/splitty/file.txt)
#module load iprscan
#module load samtools

#echo "We are in a split ${ssid}"

#for i in 0 1 2 3 4 ; do
echo ${file}
#mkdir ${file}
#cd ${file}
#mkdir splitty
#cp ../aa/${file}/best_candidates.eclipsed_orfs_removed.pep ${file}.faa
#cd splitty
#python /home/rreid2/scripts/python/oneline.py ../../../aa/${file}/best_candidates.eclipsed_orfs_removed.pep >tmp.faa
#split -l 1000 ./tmp.faa bbts

#for f in bbts*
#do

~/sw/interproscan/interproscan-5.14-53.0/interproscan.sh -i /lustre/groups/p2ep/blueberry/cran/aa/splitty/${file}  -goterms -iprlookup -seqtype p -pa  -f tsv -f XML
#  -o ${file}-iprscan.out

#done

#~/sw/interproscan-5.7-48.0/interproscan.sh -cli -i ./all1-48.fasta${file}.faa -o ${file}.iprscan.out \
#	-format raw \
#	-pa \
#	-goterms -iprlookup \
#	-seqtype p \
#	-appl hmmpanther hmmpfam superfamily
#	-appl profilescan \
#	-appl hmmpfam \
#	-appl superfamily
#done


#module load iprscan
#iprscan -cli -i ./${ssid}.fna -o ${ssid}.iprscan.out -format raw -goterms -iprlookup

echo `pwd`

