#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=20:30:23

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=12

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=85500mb

#PBS -N mmmadMatrixSkill-trinity2.2
##PBS -q bigiron


#Number of times to run this script
##PBS -t 1-21

set eu
umask 007

##home=/gpfs/fs3/home/rreid2
#cd $HOME/blueberry/reads/illumina/091230Sequence1/
#export PATH=/sw/bowtie/bin/:$HOME/bin/sopra/source_codes_v1.4.3/SOPRA_with_prebuilt_contigs:$PATH
#file=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/p2ep/oat/badassay/fastq/file.txt)
#file=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/p2ep/blueberry/rnaseq/sra-srr118/gage/file.txt)


module load bwa
module load bowtie2
module load bowtie
source ~/.bashrc

cd /lustre/groups/p2ep/blueberry/rnaseq/sra-srr118/gage/trinity2.2

#create index of reference
#bwa index -p ${file}.idx -a bwtsw /group/p2ep/blueberry/rnaseq/sra-srr118/cdhit/${file}-cdhit

module load htslib/1.1-1
module load samtools
################   Success was part below #####
#################################################		Removed the -I from bwa aln and this solves the alingment issue (casava 1.3+  vs 1.5+   #############


~/sw/trinity/trinityrnaseq-2.2.0/util/abundance_estimates_to_matrix.pl  --est_method RSEM \
--name_sample_by_basedir \
SRR1187674/RSEM.genes.results \
SRR1187632/RSEM.genes.results \
SRR1187676/RSEM.genes.results \
SRR1187673/RSEM.genes.results \
SRR1187675/RSEM.genes.results \
SRR1187677/RSEM.genes.results \
SRR1188236/RSEM.genes.results \
SRR1188242/RSEM.genes.results \
SRR1188088/RSEM.genes.results \
SRR1188091/RSEM.genes.results \
SRR1188282/RSEM.genes.results \
SRR1188258/RSEM.genes.results \
SRR1188240/RSEM.genes.results \
SRR1188247/RSEM.genes.results \
SRR1188089/RSEM.genes.results \
SRR1188283/RSEM.genes.results \
SRR1188270/RSEM.genes.results \
SRR1188090/RSEM.genes.results \
SRR1188222/RSEM.genes.results \
SRR1188230/RSEM.genes.results \
SRR1188265/RSEM.genes.results



#~/sw/trinity/trinityrnaseq-2.2.0/util/align_and_estimate_abundance.pl \
#--transcripts /group/p2ep/blueberry/rnaseq/sra-srr118/cdhit/${file}-cdhit --seqType fa \
#--single  /group/p2ep/blueberry/rnaseq/sra-srr118/filteredFasta/${file}_fastx-trim.fna \
#--thread_count 12 \
#--est_method RSEM --aln_method bowtie2 --trinity_mode --prep_reference --output_dir ${file}


#samtools import /lustre/groups/p2ep/blueberry/genomic/newblerAssembly.fna Fla4BxW85-385vsnewbler.sam  Fla4BxW85-385vsnewbler.bam

#samtools view -bS ${file}.sam | samtools sort - ${file}-sort

#samtools index ${file}-sort.bam

#samtools mpileup -ugf /lustre/groups/p2ep/oat/badassay/WG00014_OAT.targetSeq.fa ${file}-sort.bam | bcftools view -bvcg - > ${file}.bcf
#bcftools view ${file}.bcf > ${file}.vcf 

 
