#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=168:30:00

# Request 1 processor in 1 node
##PBS -l nodes=1:ppn=1

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=8GB

#PBS -N MmmakeManMiff 
##PBS -q bigiron


#Number of times to run this script
##PBS -t 1-10
##PBS -l pmem=7600mb

set eu
umask 007

cd /lustre/groups/bioservices/p2ep/blueberry/bac/sspace/
#module load blat

#1st try

perl ~/scripts/perl/make454bits50.pl 20kb


