#!/bin/bash
#PBS -N OA_ac1
#PBS -q bigiron
#PBS -l walltime=150:00:00
#PBS -l nodes=1:ppn=12
#PBS -l vmem=250g

#[[ -n "$PBS_O_WORKDIR" ]] && cd $PBS_O_WORKDIR

cd ~/p2ep/rnaseq/oases/

module load velvet/1.2.07
module load oases/0.2.08
export PATH=/lustre/sw/oases/0.2.08/scripts:$PATH

oases_pipeline.py -m 21 -M 69 -s 2 -o Vbrassica01 -d " -fasta -shortPaired ../merge/interlace-merge-V012-brass.fastq " -p " -cov_cutoff 1 -min_trans_lgth 100 -amos_file yes -unused_reads yes -alignments yes "

oases_pipeline.py -m 21 -M 69 -s 2 -o Vbrassica02 -d " -fasta -shortPaired ../merge/interlace-merge-V012-brass.fastq " -p " -cov_cutoff 2 -min_trans_lgth 100 -amos_file yes -unused_reads yes -alignments yes "

oases_pipeline.py -m 21 -M 69 -s 2 -o Vbrassica03 -d " -fasta -shortPaired ../merge/interlace-merge-V012-brass.fastq " -p " -cov_cutoff 3 -min_trans_lgth 100 -amos_file yes -unused_reads yes -alignments yes "

oases_pipeline.py -m 21 -M 69 -s 2 -o Vbrassica04 -d " -fasta -shortPaired ../merge/interlace-merge-V012-brass.fastq " -p " -cov_cutoff 4 -min_trans_lgth 100 -amos_file yes -unused_reads yes -alignments yes "

oases_pipeline.py -m 21 -M 69 -s 2 -o Vbrassica05 -d " -fasta -shortPaired ../merge/interlace-merge-V012-brass.fastq " -p " -cov_cutoff 5 -min_trans_lgth 100 -amos_file yes -unused_reads yes -alignments yes "

oases_pipeline.py -m 21 -M 69 -s 2 -o Vbrassica06 -d " -fasta -shortPaired ../merge/interlace-merge-V012-brass.fastq " -p " -cov_cutoff 6 -min_trans_lgth 100 -amos_file yes -unused_reads yes -alignments yes "

oases_pipeline.py -m 21 -M 69 -s 2 -o Vbrassica07 -d " -fasta -shortPaired ../merge/interlace-merge-V012-brass.fastq " -p " -cov_cutoff 7 -min_trans_lgth 100 -amos_file yes -unused_reads yes -alignments yes "

oases_pipeline.py -m 21 -M 69 -s 2 -o Vbrassica08 -d " -fasta -shortPaired ../merge/interlace-merge-V012-brass.fastq " -p " -cov_cutoff 8 -min_trans_lgth 100 -amos_file yes -unused_reads yes -alignments yes "

oases_pipeline.py -m 21 -M 69 -s 2 -o Vbrassica09 -d " -fasta -shortPaired ../merge/interlace-merge-V012-brass.fastq " -p " -cov_cutoff 9 -min_trans_lgth 100 -amos_file yes -unused_reads yes -alignments yes "

oases_pipeline.py -m 21 -M 69 -s 2 -o Vbrassica10 -d " -fasta -shortPaired ../merge/interlace-merge-V012-brass.fastq " -p " -cov_cutoff 10 -min_trans_lgth 100 -amos_file yes -unused_reads yes -alignments yes "



