#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=328:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=12
#PBS -l vmem=90gb

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)


#PBS -N rrrepeatMasker-bbac
#PBS -q bigiron

# launching Launching build_lmer_table on a single node so it can run till the cows come home
#echo "Launching Repeat Masker"
#export PATH=$HOME/bin:$PATH
#export PATH=$HOME/bin/RepeatMasker:$PATH
#export PATH=$HOME/bin/rmblast-1.2-ncbi-blast-2.2.23+-src/c++/GCC412-ReleaseMT64/bin:$PATH

set eu
umask 007

module load trf/4.04-1
module load ncbi-rmblast/2.2.28-1
module load hmmer/3.1b1-1
RM="/sw/packages/repeatmasker/4.0.5-1/"
export PATH="${RM}:${PATH}"
#module load repeatmasker
cd /lustre/groups/p2ep/blueberry/repeat/bac2/
#mkdir newb
#mkdir bac2
RepeatMasker -pa 12 -s -e ncbi  -dir /lustre/groups/p2ep/blueberry/repeat/bac2 -lib /lustre/groups/p2ep/blueberry/repeat/manyRep.fasta      -ace -gff /lustre/groups/p2ep/blueberry/bac/bb-011215/all6.fna
 
#mkdir garm
#RepeatMasker -pa 12 -s -e ncbi  -dir /lustre/groups/p2ep/blueberry/repeat/garm -lib /sw/packages/repeatmasker/4.0.5-1/Libraries/RepeatMasker.lib -ace -gff /lustre/groups/p2ep/blueberry/genomic/garmAssembly.fna

#-lib /home/rreid2/sw/RepeatMasker/repbase/Libraries/RepeatMaskerLib.embl





#perl /gpfs/fs3/home/rreid2/bin/RepeatMasker/RepeatMasker -pa 4 -s -lib /gpfs/fs3/home/rreid2/db/vitis/vitisRScout.out -cutoff 350 -dir /gpfs/fs3/home/rreid2/db/vitis -ace -gff /gpfs/fs3/home/rreid2/db/vitis/vitisscaffolds.fa 

