#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=296:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=1

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=7g

#PBS -N aaanoteTheOAT
##PBS -q bigiron


#Number of times to run this script
##PBS -t 1-16


name=dr2
cd /group/bioservices/hockeypuck/gm/aa/interpro/annot/ 

file=$(sed -n -e "${PBS_ARRAYID}p" /group/bioservices/hockeypuck/gm/aa/interpro/emirfile.txt)
#module load iprscan
#module load samtools

#echo "We are in a split ${ssid}"

#for i in 0 1 2 3 4 ; do
	 echo ${file}
#cd ${file}
#mkdir split
#cd split

#python /lustre/home/rreid2/scripts/python/oneline.py ../best_candidates.eclipsed_orfs_removed.pep >tmp.faa
#split -l 1000 tmp.faa ${file}


cd /group/p2ep/brassica/rnas/interpro
grep "GO:" ./all-V012-iprscan.out > go-v012
perl /home/rreid2/scripts/perl/filterInterpro-2-annot.pl go-v012

fyle=F007
grep "GO:" ./all-${fyle}-iprscan.out > go-${fyle}
perl /home/rreid2/scripts/perl/filterInterpro-2-annot.pl go-${fyle}

echo `pwd`

