#!/bin/bash
# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=380:30:00


# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=12

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=90gb

#PBS -N bbbrockLeeSoap 
##PBS -q bigiron
#Number of times to run this script
##PBS -t 1-17
##PBS -t 12-22

set -eu
umask 007


#file=$(sed -n -e "${PBS_ARRAYID}p"  /lustre/groups/bioservices/p2ep/dhmri/run4-Duke-Jan2-2014/Project_UNCC_930_131213A1/file.txt)
#file2=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/bioservices/p2ep/dhmri/run3-nov25-13/fileheader.txt)
#sed -i.orig 's/^$/N/' /lustre/groups/bioservices/p2ep/dhmri/run2-oat-brass-oct25-2013/${file}_R1_001.cutadapt.fastq
#sed -i.orig 's/^$/N/' /lustre/groups/bioservices/p2ep/dhmri/run2-oat-brass-oct25-2013/${file}_R2_001.cutadapt.fastq

#mkdir /lustre/groups/p2ep/masurca/round3/$file
#cd ~/p2ep/masurca/UNCC_Schlueter_130909HiSeq_Run_Sample_3_059_AGTCAA_L003
#rm -r ~/p2ep/masurca/$file/*
cd /lustre/groups/p2ep/brassica/soap-v158/
#mkdir ${file}
#cd ${file}
#cp ../config-run3.txt ./

#sed -i.orig -e "s/foo/${file}/g" config-run3.txt
#perl /lustre/home/rreid2/sw/MaSuRCA-2.3.2/bin/runSRCA.pl config.txt
#./assemble.sh

#module load soapdenovo2/2.04-r240
# /home/rreid2/sw/SOAPdenovo2-bin-LINUX-generic-r240/SOAPdenovo-63mer

/home/rreid2/sw/SOAPdenovo2-bin-LINUX-generic-r240/SOAPdenovo-63mer pregraph -s config.txt -K 31  -R -o graph_prefix
#/home/rreid2/sw/SOAPdenovo2-bin-LINUX-generic-r240/SOAPdenovo-127mer all -s config.txt -K 61 -p 24 -a 988  -o graph_prefix
/home/rreid2/sw/SOAPdenovo2-bin-LINUX-generic-r240/SOAPdenovo-63mer contig  -g graph_prefix -R 1>contig.log 2>contig.err

/home/rreid2/sw/SOAPdenovo2-bin-LINUX-generic-r240/SOAPdenovo-63mer map  -s config.txt -g graph_prefix 1>map.log 2>map.err

/home/rreid2/sw/SOAPdenovo2-bin-LINUX-generic-r240/SOAPdenovo-63mer scaff -g graph_prefix -F 1>scaff.log 2>scaff.err

echo -n 'All done ';date;
