#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=168:30:00

# Request 1 processor in 1 node
##PBS -l nodes=1:ppn=12

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=90GB

#PBS -N SsspaceManSpiff 
##PBS -q bigiron


#Number of times to run this script
##PBS -t 1-10
##PBS -l pmem=7600mb

set eu
umask 007

cd /lustre/groups/bioservices/p2ep/blueberry/bac/sspace/
module load bwa

#1st try
#perl /home/rreid2/sw/SSPACE-BASIC-2.0_linux-x86_64/SSPACE_Basic_v2.0.pl -l libraries2.txt -s /lustre/groups/p2ep/blueberry/garm/mas2newb/bothbinContigs.fna  -v 0 -x 1 -p 1 -k 1 -T 12  -b sspace2


#2nd try
#cd /lustre/groups/bioservices/p2ep/blueberry/bac/sspace/take2
#perl /home/rreid2/sw/SSPACE-BASIC-2.0_linux-x86_64/SSPACE_Basic_v2.0.pl -l libraries.txt -s /lustre/groups/p2ep/blueberry/garm/mas2newb/bothScafBin.fna  -v 0 -x 1 -p 1 -k 1 -T 12  -b sspace2

#cd /lustre/groups/bioservices/p2ep/blueberry/bac/sspace/take4
#perl /home/rreid2/sw/SSPACE-BASIC-2.0_linux-x86_64/SSPACE_Basic_v2.0.pl -l libraries.txt -s /lustre/groups/p2ep/blueberry/garm/mas2newb/bothbinContigs.fna  -v 0 -x 1 -p 1 -k 6 -T 12  -b sspace-bacbit


#cd /lustre/groups/bioservices/p2ep/blueberry/bac/sspace/take6
#perl /home/rreid2/sw/SSPACE-BASIC-2.0_linux-x86_64/SSPACE_Basic_v2.0.pl -l libraries.txt -s /lustre/groups/p2ep/blueberry/garm/mas2newb/bothScafBin.fna  -v 0 -x 1 -p 1 -k 6 -T 12  -b sspace-454bit


### 8th try , new sspace v3 and bacbits and 454bits
cd /lustre/groups/bioservices/p2ep/blueberry/bac/sspace/take8
perl /home/rreid2/sw/sspace/SSPACE-STANDARD-3.0_linux-x86_64/SSPACE_Standard_v3.0.pl  -l libraries.txt -s /lustre/groups/p2ep/blueberry/garm/mas2newb/bothScafBin.fna  -v 0 -x 1 -o 3 -k 2 -n 15 -T 12 -p 1 -z 0 -v 3   -b sspace-V3-454bits

#for i in {1..12}
#do

#perl ~/scripts/fq2fa.pl -a ./kohl${i}_uniq2.fastq.adapt.dup

#nucmer --maxmatch -mincluster 50 -b 100 -minmatch 10 --coords -prefix BacOnNextera ../bb-011215/all6.fna ../../genomic/masurca-nextera454.fna


#perl ~/scripts/fq2fa.pl -a ./kohl${i}_uniq1.fastq.adapt.dup

#~/sw/MUMmer3.22/nucmer --maxmatch -mincluster 50 -b 100 -minmatch 10 --coords -prefix 19ntVSreads${i} ./19nt.fa ./kohl${i}_uniq1.fastq.adapt.dup.fa

#done
