#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=148:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=8

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
##PBS -l pmem=7600mb
#PBS -l mem=64gb
#PBS -N bbbigTable-blugatti
#PBS -j oe
#PBS -q hammerhead
#Number of times to run this script
##PBS -t 1-1
set -eu
umask 007
#-j oe

#file=$(sed -n -e "${PBS_ARRAYID}p" /scratch/rreid2/italy/fastx/file.txt)
#file=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/lorainelab/data/illumina/sweet_potato/filtered/concat/file.txt)

#module load trinity/2.4.0
module load bowtie2 
#module load blast/2.5.0+  
#source ~/.bashrc

cd /scratch/rreid2/italy/align/

echo `pwd`

/apps/pkg/trinity-2.4.0/util/abundance_estimates_to_matrix.pl  --est_method eXpress \
Sample_M_B_CA_R1_1-results.xprs \
Sample_M_B_CA_R2_1-results.xprs \
Sample_M_B_CA_R3_1-results.xprs \
Sample_M_B_F_R1_1-results.xprs \
Sample_M_B_F_R2_1-results.xprs \
Sample_M_B_F_R3_1-results.xprs \
Sample_M_C_CA_R1_1-results.xprs \
Sample_M_C_CA_R2_1-results.xprs \
Sample_M_C_CA_R3_1-results.xprs \
Sample_M_C_F_R1_1-results.xprs \
Sample_M_C_F_R2_1-results.xprs \
Sample_M_C_F_R3_1-results.xprs \
Sample_M_G_R1_1-results.xprs \
Sample_M_G_R2_1-results.xprs \
Sample_M_G_R3_1-results.xprs \
Sample_M_M_R1_1-results.xprs \
Sample_M_M_R2_1-results.xprs \
Sample_M_M_R3_1-results.xprs \
Sample_M_O_R1_1-results.xprs \
Sample_M_O_R2_1-results.xprs \
Sample_M_O_R3_1-results.xprs \
Sample_M_V_R1_1-results.xprs \
Sample_M_V_R2_1-results.xprs \
Sample_M_V_R3_1-results.xprs 

### --name_sample_by_basedir

echo "FIN"


