#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=668:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=32

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
##PBS -l pmem=7600mb
#PBS -l mem=900gb
#PBS -N triii-blugatti
#PBS -j oe
#PBS -q hammerhead
#Number of times to run this script
##PBS -t 1-12

set eu
umask 007
#-j oe

#file=$(sed -n -e "${PBS_ARRAYID}p" ~/echinoderms/dl/120727B2/files.txt)
#file=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/lorainelab/data/illumina/sweet_potato/filtered/concat/file.txt)

module load trinity/2.4.0
#module load bowtie2/2.2.9 
#module load oases

cd /projects/echinotol/masurtmp/italy
echo `pwd`

#perl ~/sw/trinityrnaseq_r2013-02-25/Trinity.pl --seqType fq --JM 400G --output V012-trinity \
# --left /lustre/groups/p2ep/rnaseq/raw/merge-V012_CTTGTA_L002_R1.fastq \
# --right /lustre/groups/p2ep/rnaseq/raw/merge-V012_CTTGTA_L002_R2.fastq --CPU 8

#Trinity --seqType fq  --output giga-trinity --max_memory 890G  --single /scratch/rreid2/italy/giga/gigafiltered.fastq --CPU 32 --min_contig_length 150 --trimmomatic --full_cleanup 
 
Trinity --seqType fq  --output giga-trinity --max_memory 890G  --single /scratch/rreid2/italy/trinity/giga-trinity/gigafiltered.fastq.qtrim.fq --CPU 32 --min_contig_length 150
