
#!/bin/sh

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=168:30:00

# Request 1 processor in 1 node
##PBS -l nodes=1:ppn=1

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
##PBS -l pmem=7600mb

#PBS -N ampnosyyyy
##PBS -q bigiron


#Number of times to run this script
##PBS -t 1-48

module load ampliconnoise


##home=/gpfs/fs3/home/rreid2
cd $HOME/mel/perseus/

#export PATH=$HOME/bin/velvet_1.1.04:$PATH
#file=$(sed -n -e "${PBS_ARRAYID}p" ./filedir.txt)

ulimit -s 1000000

#cd ${file}

echo  `ls mer*` 

mpirun -np 8 SeqDist -in mergemax280.fasta > mergemax.seqdist

FCluster -in mergemax.seqdist -out mergemax 
 

SeqNoise -in mergemax280.fasta \
-din mergemax.seqdist \
-lin mergemax.list \
-s 30.0 -c 0.08  -out mergeMaxSeqNoise 

echo `pwd`


