#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=68:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=12

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=48gb
#PBS -N boootieInjections 
##PBS -q bigiron


#Number of times to run this script
#PBS -t 1-6

##home=/gpfs/fs3/home/rreid2
#cd $HOME/blueberry/reads/illumina/091230Sequence1/
#export PATH=/sw/bowtie/bin/:$HOME/bin/sopra/source_codes_v1.4.3/SOPRA_with_prebuilt_contigs:$PATH
#fyle=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/bioservices/mouse_erb2/filesmarch.txt)
fyle=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/bioservices/mouse_erb2/april/files.txt)

module load bowtie2


#cd /lustre/groups/bioservices/mouse_erb2/march/
cd /lustre/groups/bioservices/mouse_erb2/april/

bowtie2 -x /lustre/groups/bioservices/christine_richardson_mouse/iGenomes_Mus_musculus/UCSC/mm10/Sequence/Bowtie2Index/genome \
 -U ${fyle}  \
--fast \
--no-unal \
-p 12 > ${fyle}.sam



