
#!/bin/sh

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=168:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=1

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
##PBS -l pmem=7600mb

#PBS -N Q2fna 
##PBS -q bigiron


#Number of times to run this script
##PBS -t 1-10

##home=/gpfs/fs3/home/rreid2
cd $HOME/scripts/

input_file=$HOME/blueberry/reads/illumina/091005Sequence1/s_1_2_sequence.txt.trimmedkmer75v120;
output_file=$HOME/blueberry/reads/illumina/091005Sequence1/s_1_2_sequence.filtered.fna


#perl /gpfs/fs3/home/rreid2/scripts/perl/fq2fa.pl -a $HOME/blueberry/reads/hiseq/s_1_2_sequence.txt.trimmedkmer7520 > hiseqS_1_2.fasta
#perl /gpfs/fs3/home/rreid2/scripts/perl/fq2fa.pl -a $HOME/blueberry/reads/hiseq/s_2_1_sequence.txt.trimmedkmer7520 > hiseqS_2_1.fasta
perl /gpfs/fs3/home/rreid2/scripts/perl/fq2fa.pl -a $HOME/blueberry/reads/hiseq/s_2_2_sequence.txt.trimmedkmer7520 > hiseqS_2_2.fasta
