

#!/bin/sh

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=68:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=1

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
##PBS -l pmem=7600mb

#PBS -N findPairsPlus 
#PBS -q bigiron


#Number of times to run this script
##PBS -t 1-5

##home=/gpfs/fs3/home/rreid2
#cd $HOME/blueberry/reads/illumina/091230Sequence1/
export PATH=/sw/bowtie/bin/:$HOME/bin/sopra/source_codes_v1.4.3/SOPRA_with_prebuilt_contigs:$PATH


cd ~/old/blueberry/reads/hiseq/

perl ~/old/scripts/perl/findpairsPlus.pl ~/old/blueberry/reads/hiseq/s_5_1_sequence.f.fa.final3 ~/old/blueberry/reads/hiseq/s_5_2_sequence.r.fa.final3


