#!/bin/sh

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=24:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=4

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)


#PBS -N manyills 
#PBS -q bigiron


#Number of times to run this script
##PBS -t 1-6

##home=/gpfs/fs3/home/rreid2


# launching Launching build_lmer_table on a single node so it can run till the cows come home
#echo "Launching Repeat Masker"
source /sw/functions.sh
prepend_dir PATH $HOME/bin
prepend_dir PATH $HOME/scripts
prepend_dir PATH $HOME/bin/RepeatMasker

#export PATH=$HOME/bin:$PATH
#export PATH=$HOME/bin/RepeatMasker:$PATH
#export PATH=$HOME/bin/rmblast-1.2-ncbi-blast-2.2.23+-src/c++/GCC412-ReleaseMT64/bin:$PATH

basedir=$HOME/blueberry/reads/illumina/
cd $basedir

#file=$(sed -n -e "${PBS_ARRAYID}p" files2.txt)
dirNum=(2 3 4 6 7 8)
for num in ${dirNum[@]}
do
#	name=091005Sequence$num
	name=090702Seqeunce${num}
	echo $basedir$name
	cd $basedir$name
#	/sw/velvet/bin/shuffleSequences_fastq.pl s_${num}_1_sequence.txt.trimmedkmer7520 s_${num}_2_sequence.txt.trimmedkmer7520 sequencev2.shuffled

	/sw/velvet-1.1.03/bin/velveth velvet33trimmed 33 -fastq -shortPaired sequencev2.shuffled

	/sw/velvet-1.1.03/bin/velvetg velvet33trimmed -exp_cov auto -min_contig_lgth 100 -cov_cutoff auto -ins_length 100


done


