#!/bin/sh




# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=68:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=24

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=16600mb

#PBS -N ChimeraSlayyyyer 
#PBS -q bigiron


#Number of times to run this script
##PBS -t 1-10
##PBS -l pmem=7600mb



cd ~/mel/uchime/slayer/
#cd ~/mel/merge/

~/sw/mothur/mothur batch2.bat

