#!/bin/sh

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=2:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=1

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=88gb

#PBS -N  mooova 

#PBS -t 1-23

ssid=$(sed -n -e "${PBS_ARRAYID}p" /lustre/home/rreid2/blueberry/4-4exons/exon4/hitfile.txt)

#home=/gpfs/fs3/home/rreid2
cd /lustre/home/rreid2/blueberry/4-4exons/exon4

mv ../$ssid ./

