#!/bin/sh





# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=168:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=1

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l pvmem=7600mb

#PBS -N YeOldeBlastEngine


echo "Launching BlastN "

cd $HOME


***   Running on BioLinux   ***
formatdb is located on formatdb: /usr/bin/formatdb

No version here that I know of.



