#!/bin/sh

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=68:30:00

# Request 1 processor in 1 node
##PBS -l nodes=1:ppn=1

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=96600mb

#PBS -N oOOoTUpipeline
##PBS -q bigiron

#Number of times to run this script
##PBS -t 1-10
##PBS -l pmem=7600mb

cd ~/mel/uchime/
#cd ~/mel/merge/




#/lustre/home/rreid2/sw/usearch5.1.221_i86linux32 --uchime ./mergemax280.fasta --chimeras ./chimeras280_denovo.fa --nonchimeras ./nonchimeras280.fa --uchimeout ./denovo280.uchime --log ./uchimedn280.log
u=/lustre/home/rreid2/sw/usearch5.1.221_i86linux32
input=./mergemax280.fasta
output=./otupipe1


~/sw/otupipe1.1.9/otupipe.bash $input $output

