
#!/bin/sh




# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=68:30:00

# Request 1 processor in 1 node
##PBS -l nodes=1:ppn=1

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
##PBS -l pmem=7600mb

#PBS -N preentScaf 
##PBS -q bigiron


#Number of times to run this script
##PBS -t 1-10
##PBS -l pmem=7600mb

source /lustre/sw/Modules/default/init/$(basename $SHELL)

module load bambus
echo "PERL5LIB=$PERL5LIB"



##home=/gpfs/fs3/home/rreid2
cd $HOME/blueberry/mira/bambus/
#mkdir bambus

printScaff -e bambus1.evidence.xml -s bambus1.out.xml \
-l bambus1.lib -f /lustre/home/rreid2/blueberry/mira/BB_assembly/BB_d_results/BB_out.unpadded.fasta -merge -o BB3scaffold -page -dot


#goBambus -c /lustre/home/rreid2/blueberry/mira/BB_assembly/BB_d_results/BB_out.contig \
#-m ~/blueberry/mira/bambus/pairLibrary.txt \
#-x ~/blueberry/mira/BB_traceinfo_in.454.xml \
#-o bambus1 \
#-C ~/blueberry/mira/bambus/theconf.conf 
 
