#!/bin/sh





# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=168:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=1

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)


#PBS -N RepeatScoutRabid
#PBS -q bigiron

#home=/gpfs/fs3/home/rreid2


# launching Launching build_lmer_table on a single node so it can run till the cows come home
#echo "Repeat Scout"

cd $PBS_O_WORKDIR

/gpfs/fs3/home/rreid2/bin/RepeatScout-1/RepeatScout  -sequence /gpfs/fs3/home/rreid2/arabid/chr1out.trim -freq /gpfs/fs3/home/rreid2/arabid/rscout/arabid1.freq  -output /gpfs/fs3/home/rreid2/arabid/rscout/rabid1RScout.out 



