#!/bin/sh




# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=68:30:00

# Request 1 processor in 1 node
##PBS -l nodes=1:ppn=1

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
##PBS -l pmem=7600mb

#PBS -N talleeeeeBoPartner  
##PBS -q bigiron


#Number of times to run this script
##PBS -t 1-10
##PBS -l pmem=7600mb



cd ~/blueberry/tallymer/


#~/sw/gt-1.3.9-Linux_x86_64-64bit/bin/gt suffixerator -dna -pl -tis -suf -lcp -v -parts 4 -db ~/blueberry/mira/bbrep2_in.solexa.fastq -indexname readsbbHiseq

#~/sw/gt-1.3.9-Linux_x86_64-64bit/bin/gt tallymer occratio -output unique nonunique relative -mersizes 10 12 14 16 18 20 22 30 50 100 200 400  -esa readsbbHiseq > bbSolexa.dist.txt





#~/sw/gt-1.3.9-Linux_x86_64-64bit/bin/gt suffixerator -dna -pl -tis -suf -lcp -v -parts 4 -db /lustre/home/rreid2/blueberry/mira/bbrep2_assembly/bbrep2_d_results/bbrep2_out.unpadded.fasta -indexname readsbb2mira

# ~/sw/gt-1.3.9-Linux_x86_64-64bit/bin/gt tallymer occratio -output unique nonunique relative -mersizes 10 11 12 13 14 15 16 17 18 19 20 21 22 24 26 28 30 50 60 70 80 90 100 200 400 500 1000  -esa readsbb2mira > bb2mira.dist.txt






# ~/sw/gt-1.3.9-Linux_x86_64-64bit/bin/gt suffixerator -dna -pl -tis -suf -lcp -v -parts 4 -db ~/blueberry/garron/garrons454Contigs.fna -indexname readsnewbler

#~/sw/gt-1.3.9-Linux_x86_64-64bit/bin/gt tallymer occratio -output unique nonunique relative \
#       	-mersizes 10 11 12 13 14 15 16 17 18 19 20 21 22 24 26 28 30 50 60 70 80 90 100 200 400 500 1000 \
#      	-esa readsnewbler > bbNewblerContigs.dist.txt


#~/sw/gt-1.3.9-Linux_x86_64-64bit/bin/gt tallymer occratio -output unique nonunique relative \
#	        -mersizes 10 11 12 13 14 15 16 17 18 19 20 21 22 24 26 28 30 50 60 70 80 90 100 200 400 500 1000 \
#		        -esa reads > bb454.dist.txt

~/sw/gt-1.3.9-Linux_x86_64-64bit/bin/gt suffixerator -dna -pl -tis -suf -lcp -v -parts 4 -db ~/old/blueberry/db/vitisscaffolds.fa -indexname readsVitis

 ~/sw/gt-1.3.9-Linux_x86_64-64bit/bin/gt tallymer occratio -output unique nonunique relative -mersizes 10 11 12 13 14 15 16 17 18 19 20 21 22 24 26 28 30 50 60 70 80 90 100 200 400 500 1000  -esa readsVitis > vitis.dist.txt


