
#!/bin/sh

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=16:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=1

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l pmem=7600mb

#PBS -N tallyLuvSally 
##PBS -q bigiron


#Number of times to run this script
#PBS -t 1-9

##home=/gpfs/fs3/home/rreid2
#cd $HOME/blueberry/reads/illumina/091230Sequence1/
#export PATH=/sw/velvet/bin:$PATH
#/sw/velvet/bin/velveth velvet31 31 -fastq -long s_1_sequence.txt.trimmedkmer7520 

#/sw/velvet/bin/velvetg velvet31 -exp_cov auto -min_contig_lgth 100 -unused_reads yes -cov_cutoff auto 

#/sw/velvet/bin/velvetg velvet17 -exp_cov auto -min_contig_lgth 100 -unused_reads yes -cov_cutoff auto

cd ~/blueberry/tallymer/other/

ssid=$(sed -n -e "${PBS_ARRAYID}p" ./filedir.txt)

		        

	echo `pwd`


echo $ssid

~/sw/gt-1.3.9-Linux_x86_64-64bit/bin/gt suffixerator -dna -pl -tis -suf -lcp -v -parts 4 -db ~/old/db/$ssid -indexname reads$ssid

 ~/sw/gt-1.3.9-Linux_x86_64-64bit/bin/gt tallymer occratio -output unique nonunique relative -mersizes 10 11 12 13 14 15 16 17 18 19 20 21 22 24 26 28 30 50 60 70 80 90 100 200 400 500 1000  -esa reads$ssid > $ssid.dist.txt

