#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=168:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=24

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=388gb
#PBS -N aaagust-mcahare
#PBS -q hammerhead
##PBS -t 1-5

umask 007
set -eu

#ssid=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/bioservices/hockeypuck/old/blueberry/reads/hiseq/file.txt)
#dir=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/bioservices/p2ep/dhmri/run2-oat-brass-oct25-2013/filedir.txt)

echo "Launching fastx"

#cd $home
module load bamtools/2.4.1
module load augustus/3.3
module load blat

cd /nobackup/banana_genome/genesOfInterest/augustus

#blat -minIdentity=90  /group/p2ep/blueberry/genomic/sspace-take6.fna /lustre/groups/p2ep/blueberry/rnaseq/sra-srr118/alltri.fna  alltri.psl
#/lustre/sw/augustus/2.6.1/scripts/filterPSL.pl --uniq cdna.psl cdna.f.psl

#cat alltri.psl | sort -n -k 16,16 | sort -s -k 14,14 > alltri2.psl
#/lustre/sw/augustus/2.6.1/scripts/blat2hints.pl --in=alltri2.psl --out=hints.E.gff

#--hintsfile=hints.EE.gff \
#--extrinsicCfgFile=./myextrinsic.cfg \

augustus  --species=tomato \
/scratch/rreid2/banana/denovo/mchare-abyss-scaffolds.fa   \
--outfile=aug-mchare.gff \
--genemodel=partial \
--singlestrand=true \
--protein=on \
--introns=on \
--start=on \
--stop=on \
--cds=on \
--UTR=off \
--codingseq=on \
--gff3=on \
--noInFrameStop=true

#--extrinsicCfgFile=./myextrinsic.cfg \

##### ROund 1  ######  with no est or protein evidence

#augustus  --species=arabidopsis \
# 39  /lustre/groups/p2ep/brassica/annot/referenceGenome/boleracea.v1.genome.fasta  \
# 40 --outfile=aug-brass-ref \
# 41 --genemodel=partial \
# 42 --singlestrand=true \
# 43 --protein=on \
# 44 --introns=on \
# 45 --start=on \
# 46 --stop=on \
# 47 --cds=on \
# 48 --UTR=off \
# 49 --codingseq=on \
# 50 --gff3=on \
# 51 --noInFrameStop=true
#
echo "FIN"


