#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=168:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=4

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=36gb
#PBS -j oe
#PBS -N fffilterVCF-banana
#PBS -q hammerhead
#PBS -t 1-20
umask 007
set -eu

file=$(sed -n -e "${PBS_ARRAYID}p" /scratch/rreid2/banana/filter/trimgalore/file.txt)
#dir=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/lorainelab/data/illumina/sweet_potato/filtered/dir.txt)

echo "Launching BWA alignment"

#module load java8 
#module load samtools
#module load bwa
#module load bcftools


cd /scratch/rreid2/banana/align/run3 

python /users/rreid2/scripts/python/filterVCF-byDP-banana.py ${file}-filth.vcf 50









