#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=468:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=64

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=464gb
#PBS -j oe
#PBS -N gggatk-unified-noplantain
#PBS -q hammerhead
##PBS -t 1-20
umask 007
set -eu

#file=$(sed -n -e "${PBS_ARRAYID}p" /scratch/rreid2/banana/filter/trimgalore/file.txt)
#dir=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/lorainelab/data/illumina/sweet_potato/filtered/dir.txt)

echo "Launching GATK haplotyper"

#module load java8 
#module load samtools
#module load bwa
#module load bcftools
module load gatk

cd /scratch/rreid2/banana/gatk/

java -jar /apps/pkg/gatk-3.8/GenomeAnalysisTK.jar \
 --analysis_type HaplotypeCaller \
 -R /scratch/rreid2/banana/db/bananagenomehub/pahang-v2/musa_acuminata_v2_pseudochromosome.fna \
 -I /scratch/rreid2/banana/align/run3/readgrouped-1121_S14_L004-sorted.bam \
 -I /scratch/rreid2/banana/align/run3/readgrouped-1187_S15_L004-sorted.bam \
 -I /scratch/rreid2/banana/align/run3/readgrouped-1254_S16_L004-sorted.bam \
 -I /scratch/rreid2/banana/align/run3/readgrouped-1354_S7_L002-sorted.bam \
 -I /scratch/rreid2/banana/align/run3/readgrouped-1437_S38_L008-sorted.bam \
 -I /scratch/rreid2/banana/align/run3/readgrouped-1466_S2_L001-sorted.bam \
 -I /scratch/rreid2/banana/align/run3/readgrouped-1468_S3_L001-sorted.bam \
 -I /scratch/rreid2/banana/align/run3/readgrouped-249_S39_L008-sorted.bam \
 -I /scratch/rreid2/banana/align/run3/readgrouped-253_S5_L002-sorted.bam \
 -I /scratch/rreid2/banana/align/run3/readgrouped-281_S6_L002-sorted.bam \
 -I /scratch/rreid2/banana/align/run3/readgrouped-299_S8_L002-sorted.bam \
 -I /scratch/rreid2/banana/align/run3/readgrouped-425_S1_L001-sorted.bam \
 -I /scratch/rreid2/banana/align/run3/readgrouped-591_S4_L001-sorted.bam \
 -I /scratch/rreid2/banana/align/run3/readgrouped-653_S9_L003-sorted.bam \
 -I /scratch/rreid2/banana/align/run3/readgrouped-654_S10_L003-sorted.bam \
 -I /scratch/rreid2/banana/align/run3/readgrouped-712_S11_L003-sorted.bam \
 -I /scratch/rreid2/banana/align/run3/readgrouped-766_S12_L003-sorted.bam \
 -I /scratch/rreid2/banana/align/run3/readgrouped-966_S13_L004-sorted.bam \
 -o noplantain.raw.vcf \
 -stand_call_conf 50 \
 -ploidy 40 \
 --min_base_quality_score 15 \
 -nct 64


###### Removed Plantains !!!   #########
#-I /scratch/rreid2/banana/align/run3/readgrouped-109_S36_L008-sorted.bam \
# 35  -I /scratch/rreid2/banana/align/run3/readgrouped-111_S37_L008-sorted.bam \




#python /users/rreid2/scripts/python/filterVCF-bygene-banana.py ${file}-filth-byDP.vcf musa_acuminata_v2-mRNA.gff3

#awk '{print $1 "\t" $2 "\t" $5 }' ${file}-filth-byDP-byGeneLocation-v2.vcf > ${file}-just3cols.txt







