#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=468:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=64

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=464gb
#PBS -j oe
#PBS -N cccalc-indie
#PBS -q hammerhead
#PBS -t 1-7
umask 007
set -eu

file=$(sed -n -e "${PBS_ARRAYID}p" /nobackup/banana_genome/indieVCF/filediploid.txt)
#dir=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/lorainelab/data/illumina/sweet_potato/filtered/dir.txt)

echo "Launching GATK haplotyper"

#module load java8 
#module load samtools
#module load bwa
#module load bcftools
module load gatk

cd /nobackup/banana_genome/indieVCF


python /users/rreid2/scripts/python/calcAF-fromVCF.py /nobackup/banana_genome/snppicker/master/megamaster-v2.txt /nobackup/banana_genome/indieVCF/${file}-sorted.raw.vcf

####  Picking from the just7-14 subset
cd /nobackup/banana_genome/indieVCF/just7-14
python /users/rreid2/scripts/python/calcAF-fromVCF.py /nobackup/banana_genome/snppicker/master/just7-14-locations.txt /nobackup/banana_genome/indieVCF/${file}-sorted.raw.vcf





