#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=168:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=12

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=88gb
#PBS -j oe
#PBS -N tttrimit-postGalore
#PBS -q hammerhead
#PBS -t 1-20
umask 007
set -eu

file=$(sed -n -e "${PBS_ARRAYID}p" /scratch/rreid2/banana/filter/trimgalore/file.txt)
#dir=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/lorainelab/data/illumina/sweet_potato/filtered/dir.txt)

echo "Launching fastx"

#cd $home
#module load java8 

cd /scratch/rreid2/banana/filter/trimmomatic/trimgalored 


java -jar ~/sw/trimmomatic/Trimmomatic-0.36/trimmomatic-0.36.jar PE -threads 24 ../../trimgalore/${file}_R1_001_val_1.fq ../../trimgalore/${file}_R2_001_val_2.fq output_${file}-R1_paired.fq output_${file}-R1_unpaired.fq output_${file}-R2_paired.fq output_${file}-R2_unpaired.fq ILLUMINACLIP:TruSeq2-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:50

#	fastq_quality_trimmer -Q33 -v -t 20 -i ./BJ31-R1.fastq -o BJ31-R1_fastxqual.fastq
#	fastq_quality_trimmer -Q33 -v -t 20 -i ./BJ31-R2.fastq -o BJ31-R2_fastxqual.fastq
#        fastx_quality_stats -Q33 -i BJ31-R1_fastxqual.fastq -o BJ31-R1_fastxqual_qualstats.txt
#	fastx_quality_stats -Q33 -i BJ31-R2_fastxqual.fastq -o BJ31-R2_fastxqual_qualstats.txt

####  Validate Mate pairs   ######
#perl ~/scripts/perl/validateHiseqPairs.pl BJ31-R1_fastxqual.fastq BJ31-R2_fastxqual.fastq







