

#!/bin/sh

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=68:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=4

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=15500mb

#PBS -N Bwaaaaacholine 
##PBS -q bigiron

#Number of times to run this script
#PBS -t 1-37

##home=/gpfs/fs3/home/rreid2
#cd $HOME/blueberry/reads/illumina/091230Sequence1/
#export PATH=/sw/bowtie/bin/:$HOME/bin/sopra/source_codes_v1.4.3/SOPRA_with_prebuilt_contigs:$PATH
ssid=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/bioservices/hockeypuck/corbin/filepair2.txt)

#module load bwa
cd /lustre/groups/bioservices/hockeypuck/corbin/

mkdir ${ssid}

cd /lustre/groups/bioservices/hockeypuck/corbin/${ssid}/
echo "`pwd`"

cat  ../C1963ACXX_s3_1_GSLv2-7_${ssid}/C1963ACXX_s3_1_GSLv2-7_${ssid}.fastq.adapt.dup ../C1963ACXX_s4_1_GSLv2-7_${ssid}/C1963ACXX_s4_1_GSLv2-7_${ssid}.fastq.adapt.dup > ${ssid}_1_filtered.fastq

cat  ../C1963ACXX_s3_2_GSLv2-7_${ssid}/C1963ACXX_s3_2_GSLv2-7_${ssid}.fastq.adapt.dup ../C1963ACXX_s4_2_GSLv2-7_${ssid}/C1963ACXX_s4_2_GSLv2-7_${ssid}.fastq.adapt.dup > ${ssid}_2_filtered.fastq 

