#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=168:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=12

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=88gb

#PBS -N tttophat-cote

#PBS -t 1-18
umask 007
set -eu

file=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/bioservices/gregory/HSMS_104_Cote/file2.txt)

echo "Launching tophat on ${file}"

#cd $home
module load tophat
module load bowtie2
module load cufflinks

cd /lustre/groups/bioservices/gregory/HSMS_104_Cote/tophat/

#ln -s ../${file}-R1-clip.fq_matched.fq $file-R1-filtered.fastq
#ln -s ../${file}-R2-clip.fq_matched.fq $file-R2-filtered.fastq


tophat --output-dir ${file} -p 12  ~/db/human/Homo_sapiens/UCSC/hg19/Sequence/Bowtie2Index/genome ../filter/${file}-R1-clip.fq_matched.fq ../filter/${file}-R2-clip.fq_matched.fq



cufflinks -o cufflinks_${file} ${file}/accepted_hits.bam






