#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=168:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=12

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l mem=88gb
#PBS -N tttophat-12tomates
#PBS -j oe
#PBS -q steelhead

#PBS -t 1-12
umask 007
set -eu

file=$(sed -n -e "${PBS_ARRAYID}p"  /nobackup/banana_genome/tomato/sra/srafiles.txt)

echo "Launching tophat on ${file}"

#cd $home
module load tophat
module load bowtie2
module load cufflinks

cd /nobackup/banana_genome/tomato/tophat

echo ${file}
#ln -s ../${file}-R1-clip.fq_matched.fq $file-R1-filtered.fastq
#ln -s ../${file}-R2-clip.fq_matched.fq $file-R2-filtered.fastq


tophat --output-dir ${file} -p 12 /nobackup/banana_genome/tomato/publicData/cornell-wholegenome/LYCO3  ../sra/${file}.fasta



cufflinks -o cufflinks_${file} ${file}/accepted_hits.bam






