#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=296:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=1

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=7g

#PBS -N iiinterproSwepot
##PBS -q bigiron


#Number of times to run this script
#PBS -t 1-128

cd /lustre/groups/lorainelab/data/illumina/sweet_potato/interpro/cdhit/ 

file=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/lorainelab/data/illumina/sweet_potato/cdhit/aa/split/file.txt)
#module load iprscan
#module load samtools

#echo "We are in a split ${ssid}"

#for i in 0 1 2 3 4 ; do
	 echo ${file}
~/sw/interproscan-5.7-48.0/interproscan.sh -i /lustre/groups/lorainelab/data/illumina/sweet_potato/cdhit/aa/split/${file} -o ${file}-iprscan.out  -goterms -iprlookup -seqtype p -pa -appl Panther-9.0,PfamA-27.0,PrositeProfiles-20.97 -f tsv


#~/sw/interproscan-5.7-48.0/interproscan.sh -cli -i ./all1-48.fasta${file}.faa -o ${file}.iprscan.out \
#	-format raw \
#	-pa \
#	-goterms -iprlookup \
#	-seqtype p \
#	-appl hmmpanther hmmpfam superfamily
#	-appl profilescan \
#	-appl hmmpfam \
#	-appl superfamily
#done


#module load iprscan
#iprscan -cli -i ./${ssid}.fna -o ${ssid}.iprscan.out -format raw -goterms -iprlookup

echo `pwd`

