#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=68:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=12

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=15500mb

#PBS -N deeekoder-giga 
##PBS -q bigiron


#Number of times to run this script
##PBS -t 1-7

##home=/gpfs/fs3/home/rreid2
#cd $HOME/blueberry/reads/illumina/091230Sequence1/
#file=$(sed -n -e "${PBS_ARRAYID}p" ~/p2ep/brassica/3path/file.txt)


cd /lustre/groups/lorainelab/data/illumina/sweet_potato/giga-aa/ 
#cd /lustre/groups/bioservices/p2ep/brassica/rnas/
#perl ~/sw/transdecoder_r2012-08-15/transcripts_to_best_scoring_ORFs.pl -t SOMETRANSCRIPT.fna -m 100 --CPU 15 --search_pfam ~/db/Pfam-B.hmm
#mkdir ${file}
#cd ${file}

#perl ~/sw/transdecoder_r2012-08-15/transcripts_to_best_scoring_ORFs.pl -t ../all6pathways.fna -m 30 --CPU 12 --retain_long_orfs 150 --search_pfam /lustre/home/rreid2/db/Pfam-B.hmm 

perl ~/sw/transdecoder_r2012-08-15/transcripts_to_best_scoring_ORFs.pl -t ../gigatrinity-part3/giga/Trinity.fasta -m 100 --CPU 12  --search_pfam /lustre/home/rreid2/db/Pfam-B.hmm 

