#!/bin/sh





# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=68:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=1

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
##PBS -l pvmem=7600mb

#PBS -N bbblast2table
#PBS -q bigiron

home=/gpfs/fs3/home/rreid2


# launching compare-to-gff.prl on a single node so it can run till the cows come home
echo "Launching BlastN "

#cd $HOME/scripts/perl/
cd ~/blueberry/bbBlastNT/

perl $HOME/scripts/perl/blast2Table.pl -format 7 -expect 0.1 -header -bits -verbose temp5.out temp1.out 


