#!/bin/bash

# Request a run time of x hours and x minutes
#PBS -l walltime=168:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=12

# Request x  megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=90gb

#PBS -N nnnextclip-runW85

##PBS -t 1-20
umask 007
set -eu

#file=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/bioservices/p2ep/dhmri/run1-oat-blue-oct-2013/raw_reads/file2.txt)

echo "Launching nextclip"

#cd $home

cd /lustre/groups/bioservices/p2ep/dhmri/run1-oat-blue-oct-2013/nextclip/

/lustre/groups/bioservices/p2ep/sw/nextclip-master/bin/nextclip --input_one ../raw_reads/UNCC_Schlueter_130909HiSeq_Run_Sample_W85_23_AGTTCC_L001_R1_001.fastq \
 --input_two ../raw_reads/UNCC_Schlueter_130909HiSeq_Run_Sample_W85_23_AGTTCC_L001_R2_001.fastq \
 --output_prefix W85_23_AGTTCC_L001 --log log.txt --min_length 25 --number_of_reads 52109199  --trim_ends 0 --remove_duplicates

cat W85_23_AGTTCC_L001_A_R1.fastq W85_23_AGTTCC_L001_B_R1.fastq W85_23_AGTTCC_L001_C_R1.fastq > W85_23_AGTTCC_L001_all_R1.fastq
cat W85_23_AGTTCC_L001_A_R2.fastq W85_23_AGTTCC_L001_B_R2.fastq W85_23_AGTTCC_L001_C_R2.fastq > W85_23_AGTTCC_L001_all_R2.fastq
cat W85_23_AGTTCC_L001_D_R1.fastq W85_23_AGTTCC_L001_D_R1.fastq > W85_23_AGTTCC_L001-Dcombined.fastq
rm log.txt


echo "fin"

