

#!/bin/sh

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=68:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=4

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=75500mb

#PBS -N oooorthoPolo 
##PBS -q bigiron


#Number of times to run this script
##PBS -t 1-18

##home=/gpfs/fs3/home/rreid2
#cd $HOME/blueberry/reads/illumina/091230Sequence1/
#ssid=$(sed -n -e "${PBS_ARRAYID}p" ~/echinoderms/ortho/files.txt)


cd ~/echinoderms/ortho/mafft/ 

module load mafft

mafft --auto --amino  ../15-18orthgroups/all18/ORTHOMCL110.faa > 18-ORTHOMCL110.mafft
mafft --auto --amino  ../15-18orthgroups/all18/ORTHOMCL12.faa > 18-ORTHOMCL12.mafft


