#!/bin/bash

# Request a run time of x hours and x minutes
#PBS -l walltime=168:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=12

# Request x  megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=95gb

#PBS -N followthewhiterabbit
##PBS -q bigiron
#PBS -t 1-6
umask 007
set -eu

ssid=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/bioservices/p2ep/rnaseq/parents/file.txt)
#ssid=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/bioservices/p2ep/dhmri/run7-feb17-14/rawreads/file.txt)
echo "Launching fastx"

#cd $home
module load fastx-toolkit

cd /lustre/groups/bioservices/p2ep/rnaseq/parents/fastx/

#gunzip *.gz

	echo "${ssid}"
	#gunzip ../${ssid}_R${i}_001.fastq.gz
	fastq_quality_trimmer -Q33 -v -t 20 -l 20 -i ../${ssid}.fastq -o ${ssid}_trimmed.fastq
	fastx_clipper -Q33 -a ATTGGCTTTGGGCAT -a AGTCAA -a CTTGTA -a CAGATC -a GCCAAT -a TGACCA -a ACAGTG -l 40 -n -v -i ${ssid}_trimmed.fastq -o ${ssid}_trimmed_clipped.fastq
	#mv ${ssid}_trimmed_clipped.fastq ../trimmed_clipped/
       # fastx_collapser -Q33 -v -i  ${ssid}_trimmed_clipped.fastq -o ${ssid}_collapsed.txt
        #/lustre/home/rreid2/scripts/stan/Scripts for SFG/fastqduplicatecounter.py ${ssid}_collapsed.txt ${ssid}_collapsed_headers.txt >> ${ssid}_R${i}_duplicateCount.txt
        #fastx_quality_stats -Q33 -i ${ssid}_R${i}_trimmed_clipped.fastq -o ${ssid}_R${i}_qualstats.txt




echo "fin"

