#!/bin/bash


# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=96:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=12

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=91gb

#PBS -N bbblastMito
##PBS -q bigiron
##PBS -t 1-306

#ssid=$(sed -n -e "${PBS_ARRAYID}p" ~/old/blueberry/reads/hiseq/split/files.txt)
umask 007
set eu

# launching compare-to-gff.prl on a single node so it can run till the cows come home
echo "Launching BlastP "

#cd $home
#module load ncbi-blast+

#cd /lustre/groups/janieslab/trinityRun2/orthomcl/
#cd $TMPDIR
cd /lustre/groups/janieslab/blasted/ 

#cp /lustre/groups/janieslab/trinityRun2/orthomcl/all1-48.fasta* ./
#makeDB
 module load ncbi-blast+
#makeblastdb -in /lustre/groups/janieslab/minion2/nemaReads-Jan2015.fna -dbtype nucl
#module load ncbi-blast+
#blastp -db /lustre/groups/janieslab/trinityRun2/orthomcl/all1-48.fasta -query neuro9.faa  -out neuro9VSall.blastp.txt -num_threads 24  -evalue 1e-1 -soft_masking false  -outfmt 6


blastn -db /lustre/groups/janieslab/minion2/nemaReads-Jan2015.fna -query /lustre/groups/janieslab/minion2/GenBank_Nv_all_genes.fasta   -out genbank-nv-allVSnemaReads-blastn.txt -num_threads 24  -evalue 1e-1 -soft_masking false  -outfmt 6

blastn -db /lustre/groups/janieslab/minion2/nemaReads-Jan2015.fna -query /lustre/groups/janieslab/minion2/GenBank_Nv_genes_no_drafts.fasta   -out genbank-nvGenesNodraftVSnemaReads-blastn.txt -num_threads 24  -evalue 1e-1 -soft_masking false  -outfmt 6


echo "fin"
#mv outfast.blastp.txt /lustre/groups/janieslab/trinityRun2/orthomcl/outfast.blastp.txt
