#!/bin/bash


# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=96:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=12

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=91gb

#PBS -N bbblaststrpur
##PBS -q bigiron
##PBS -t 1-306

#ssid=$(sed -n -e "${PBS_ARRAYID}p" ~/old/blueberry/reads/hiseq/split/files.txt)
umask 007
set eu

# launching compare-to-gff.prl on a single node so it can run till the cows come home
echo "Launching BlastP "

#cd $home
#module load ncbi-blast+

#cd /lustre/groups/janieslab/trinityRun2/orthomcl/
#cd $TMPDIR
cd /lustre/groups/janieslab/blasted/strpur

#cp /lustre/groups/janieslab/trinityRun2/orthomcl/all1-48.fasta* ./
#makeDB

#/lustre/sw/ncbi-blast+/2.2.25/bin/makeblastdb -in all1-48.fasta -dbtype prot

/lustre/sw/ncbi-blast+/2.2.25/bin/blastp -db /lustre/groups/janieslab/trinityRun2/orthomcl/all1-48.fasta -query strpur.faa  -out str.blastp.txt -num_threads 24  -evalue 1e-25 -soft_masking false  -outfmt 6


#mv outfast.blastp.txt /lustre/groups/janieslab/trinityRun2/orthomcl/outfast.blastp.txt
