#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=168:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=12

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=88gb

#PBS -N bbblastOutgroups2Ortho

##PBS -t 1-23

i=18

#ssid=$(sed -n -e "${PBS_ARRAYID}p" /lustre/home/rreid2/echinoderms/ortho/15-18orthgroups/all${i}/file.txt)

#home=/gpfs/fs3/home/rreid2


# launching compare-to-gff.prl on a single node so it can run till the cows come home
echo "Launching BlastP "

#cd $home
#module load ncbi-blast+

cd /lustre/home/rreid2/echinoderms/ortho/otherOutgroups/

#cd /lustre/home/rreid2/echinoderms/dl/120727B2/
####    #makeDB#####

#/lustre/sw/ncbi-blast+/2.2.25/bin/makeblastdb -in cbf1.faa -dbtype prot
#/lustre/sw/ncbi-blast+/2.2.25/bin/blastx -db cbf1.faa -query /lustre/home/rreid2/blueberry/garron/454Scaffolds.fna  -out ./garronVScbf1.blastx.xml -num_threads 1  -evalue 1e-10 -soft_masking false  -outfmt 5

#for i in 15 16 17 18
#do

	/lustre/sw/ncbi-blast+/2.2.25/bin/makeblastdb -in ~/echinoderms/db/big3outgroup.faa -dbtype prot
#done

/lustre/sw/ncbi-blast+/2.2.25/bin/blastp -db ~/echinoderms/db/big3outgroup.faa -query ../blastdir/allbj.faa  -out allbj.faa.blastp.xml -num_threads 24  -evalue 1e-3 -soft_masking false  -outfmt 5

perl ~/scripts/perl/parseOutgroupBlast.pl allbj.faa.blastp.xml
