#!/bin/sh





# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=168:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=12

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=48gb

#PBS -N GnnnnnFkitSrsly

##PBS -t 1-12

#ssid=$(sed -n -e "${PBS_ARRAYID}p" ~/echinoderms/dl/first6/files.txt)
#ssid=$(sed -n -e "${PBS_ARRAYID}p" ~/echinoderms/dl/120727B2/files.txt)


echo "Launching BlastN "

#cd $home

#/sw/ncbi-blast/bin/blastn -outfmt 6 -query ~/db/blueberry/blueRScout.out -db ~/db/vitis/vitisscaffolds.fa -out /gpfs/fs3/home/rreid2/blueberry/bbBlastedVitisGenome/bbRscoutVSvitisgenome-mega.out -task megablast -evalue 0.00001 -soft_masking false


#module load ncbi-blast+

#cd /lustre/home/rreid2/echinoderms/strongyl/
#cd /lustre/home/rreid2/echinoderms/db/
cd /lustre/home/rreid2/echinoderms/ortho

perl ~/old/scripts/perl/ortho2fasta.pl SOMEORTH.out aa/allbj.header.faa

