#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=68:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=6

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=75500mb

#PBS -N tttritties-qc 
#PBS -q bigiron

umask 007
set eu

#Number of times to run this script
##PBS -t 2-24

##home=/gpfs/fs3/home/rreid2
#cd $HOME/blueberry/reads/illumina/091230Sequence1/
#ssid=$(sed -n -e "${PBS_ARRAYID}p"  /lustre/groups/janieslab/trinityRun2/file.txt)

module load bowtie
module load samtools
#cd ~/echinoderms/ortho/test 

for ssid in BJ30 BJ31 BJ34 BJ35 BJ36 BJ37 BJ38 BJ41 BJ44 BJ39 BJ40 BJ42 BJ46 BJ43 BJ45 BJ47 BJ48 BJ32 BJ33 BJ25 BJ26 BJ27 BJ28 BJ29 
do
cd /lustre/groups/janieslab/trinityRun2/bam/

#mkdir ${ssid}


cd ${ssid}/bowtie_out
echo `pwd`

~/sw/trinityrnaseq_r2013-02-25/util/SAM_nameSorted_to_uniq_count_stats.pl bowtie_out.nameSorted.sam > ../../qc-${ssid}.txt
 samtools idxstats bowtie_out.coordSorted.bam > ../../readspercontig-${ssid}.txt

done


echo "fin"

