#!/bin/bash
#PBS -l walltime=96:00:00  # Maximum amount of real time for the job to run in HH:MM:SS
#PBS -l nodes=1:ppn=64     # Number of nodes and processors per node requested by job
#PBS -l mem=1800GB           # Maximum physical memory to use for jobi
#PBS -N sssmrt-canu          # User-defined name for job
#PBS -j oe                # Write STDERR to STDOUT output file
#PBS -q hammerhead        # Job queue to submit this script to

# User prologue.  Must be owned by user, not writable by group or other
##PBS -l prologue=/projects/oat_genome/scripts/prologue.sh
# User epilogue.  Must be owned by user, not writable by group or other
##PBS -l epilogue=/projects/oat_genome/scripts/epilogue.sh

IFS=$'\n'          # Internal Field Separator is newline
set -eu            # e - Exit on error
                   # u - Undefined variable is an error
                   # x - enable trace (print commands before running)
umask 007          # user  - all permissions
                   # group - all permissions
                   # other - no permissions
shopt -s nullglob  # Treat empty glob (*) as nothing instead of empty string

#module list
echo "WTF"

cd /nobackup/echinotol/smartDenovo

/users/rreid2/sw/smartdenovo/smartdenovo/smartdenovo.pl /nobackup/echinotol/smartDenovo/all.fna  > wtasm.mak 

make -f wtasm.mak



