#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=168:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=8

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
##PBS -l pmem=7600mb
#PBS -l vmem=400gb
#perl ~/old/scripts/perl/nucmerCoordParserBlueberry.pl $ssid.mito.coords  /lustre/home/rreid2/old/blueberry/reads//$ssid

#PBS -N triiiiEchino
#PBS -q bigiron


#Number of times to run this script
#PBS -t 1-18

#file=$(sed -n -e "${PBS_ARRAYID}p" ~/echinoderms/dl/120727B2/files.txt)
file=$(sed -n -e "${PBS_ARRAYID}p" ~/echinoderms/trimmed/file.txt)

module load bowtie
#module load oases

cd ~/echinoderms/trimmed/
echo `pwd`

perl ~/sw/trinityrnaseq_r2013-02-25/Trinity.pl --seqType fq --JM 400G --output ${file}tri --left ${file}_R1.fastq.adapt.trimmed  --right ${file}_R2.fastq.adapt.trimmed --CPU 8

