#!/bin/sh

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=98:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=6

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)


#PBS -N gmSeqcleanGM454
#PBS -q bigiron

##home=/gpfs/fs3/home/rreid2


# launching Launching build_lmer_table on a single node so it can run till the cows come home
#echo "Launching Repeat Masker"
export PATH=$HOME/bin:$PATH

cd ~/old/gm/data/454reads/  


for file in $(find ./ -name "*.fasta");
do
        echo   ${file};
#	  /lustre/home/rreid2/sw/seqclean-x86_64/seqclean $file -c 6  -v ~/old/blueberry/db/gSe13andUnivec.fasta  -o ${file}".clean"	
	 /lustre/home/rreid2/sw/seqclean-x86_64/cln2qual ${file}".cln" ${file}".qual"

	 # lucy -o ${file}.clean.lucy ${file}.qual.clean.lucy ${file}".clean" ${file}.qual.clean


done

#file=/gpfs/fs3/home/rreid2/blueberry/reads/454Sequences/OLDseqclean/level2/FQ55CRL01.fasta;
#/gpfs/fs3/home/rreid2/bin/seqclean/seqclean $file -c 8 -s /gpfs/fs3/home/rreid2/db/vitis/chloroplast/vitisviniferisChloroplastgenome.fna 



#./seqclean  ~/blueberry/reads/454Sequences/mira9/split_1.fasta -n 10 -v ~/blueberry/db/vitisViniChloro.fasta, $HOME/blueberry/db/gSe13andUnivec.fasta  -l 40  -o test -r rtest

#/gpfs/fs3/home/rreid2/bin/seqclean/seqclean $file -c 16  -v $HOME/blueberry/db/gSe13andUnivec.fasta -s $HOME/blueberry/db/vitisMito.fasta, $HOME/blueberry/db/vitisViniChloro.fasta  -l 40  -o ${file%fasta}"clean"



