#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=168:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=8

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
##PBS -l pmem=7600mb
#PBS -l vmem=400gb

#PBS -N triiiigrass
#PBS -q bigiron

#Number of times to run this script
#PBS -t 1-33

#file=$(sed -n -e "${PBS_ARRAYID}p" ~/echinoderms/dl/120727B2/files.txt)
file=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/bioservices/hockeypuck/gm/trinity/file.txt)

module load bowtie
#module load oases

cd /lustre/groups/bioservices/hockeypuck/gm/trinity/
echo `pwd`

perl ~/sw/trinityrnaseq_r2013-02-25/Trinity.pl --seqType fq --JM 400G --output ${file}tri --single ${file}  --CPU 8

