
#!/bin/sh

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=68:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=1

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
##PBS -l pmem=7600mb

#PBS -N GMVelvetBand
#PBS -q bigiron
module load velvet

#Number of times to run this script
##PBS -t 1-32

##home=/gpfs/fs3/home/rreid2
#cd $HOME/blueberry/reads/illumina/091230Sequence1/
export PATH=/sw/velvet/bin:$PATH
#/sw/velvet/bin/velveth velvet31 31 -fastq -long s_1_sequence.txt.trimmedkmer7520 

#/sw/velvet/bin/velvetg velvet31 -exp_cov auto -min_contig_lgth 100 -unused_reads yes -cov_cutoff auto 

#/sw/velvet/bin/velvetg velvet17 -exp_cov auto -min_contig_lgth 100 -unused_reads yes -cov_cutoff auto

cd ~/old/gm/assembly2/

#file=$(sed -n -e "${PBS_ARRAYID}p" ./filenames.txt)

#file="velvet"${num};
echo   ${file};

#/sw/velvet-1.1.03/bin/velveth velvet63trimmed 63 -fastq -shortPaired $HOME/blueberry/reads/illumina/091005Sequence1/sequencev2.shuffled

#num=21;
#while [ $num -le 88 ]
#do

	 #mkdir ${file%.fastq.dup.trim20}
        /lustre/sw/velvet/1.1.05/bin/velveth jb3 49  -short -fastq ../jb3.fastq.trim20
        /lustre/sw/velvet/1.1.05/bin/velvetg jb3 -read_trkg yes

#        num=`expr $num + 2`;

#done



#/sw/velvet/bin/shuffleSequences_fastq.pl s_1_1_sequence.txt.trimmedkmer75v120 s_1_2_sequence.txt.trimmedkmer75v120 sequencev2.shuffled

#echo Starting velvetH
#/sw/velvet/contrib/VelvetOptimiser-2.1.7/VelvetOptimiser.pl -s 45 -e 65 -f ' -fastq -shortPaired /gpfs/fs3/home/rreid2/blueberry/reads/illumina/091005Sequence1/sequencev2.shuffled'
#/sw/velvet-1.1.03/bin/velveth velvet63trimmed 63 -fastq -shortPaired $HOME/blueberry/reads/illumina/091005Sequence1/sequencev2.shuffled

#cd /gpfs/fs3/home/rreid2/gm/assembly2/
echo `pwd`

