#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=168:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=24

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=388gb

#PBS -N eugeneMahk-straw
#PBS -q bigiron

##PBS -t 1-5
umask 007
set -eu

#ssid=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/bioservices/hockeypuck/old/blueberry/reads/hiseq/file.txt)
#dir=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/bioservices/p2ep/dhmri/run2-oat-brass-oct25-2013/filedir.txt)

echo "Launching fastx"

#cd $home
module load genemarks/2.5m

for i in {1..7};
do

	cd /lustre/groups/p2ep/strawberry/annot/

	gm  -m /lustre/groups/p2ep/strawberry/fromGDR/temp/straw-genemark-matrix.txt ../fromGDR/fvesca_v1.1_FC${i}.fna
done





