#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=168:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=12

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=92gb

#PBS -N aaagust-cosmid

##PBS -t 1-5
umask 007
set -eu

#ssid=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/bioservices/hockeypuck/old/blueberry/reads/hiseq/file.txt)
#dir=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/bioservices/p2ep/dhmri/run2-oat-brass-oct25-2013/filedir.txt)

echo "Launching fastx"

#cd $home
module load augustus
module load blat

cd /lustre/groups/bioservices/secure/syngenta/working/rob/cosmid/augustus
#blat -minIdentity=92  ../HF050.fna /lustre/groups/bioservices/secure/syngenta/working/rob/cosmid/pvirg/Pvirgatum_273_v1.1.transcript.fna  cdna.psl
#/lustre/sw/augustus/2.6.1/scripts/filterPSL.pl --uniq cdna.psl cdna.psl

#cat cdna.f.psl | sort -n -k 16,16 | sort -s -k 14,14 > cdna2.psl


#/lustre/sw/augustus/2.6.1/scripts/blat2hints.pl --in=cdna.psl --out=hints.E.gff

#--hintsfile=/lustre/groups/bioservices/secure/syngenta/working/rob/cosmid/augustus/hints.E.gff \
#--extrinsicCfgFile=/lustre/groups/bioservices/secure/syngenta/working/rob/cosmid/myextrinsic.cfg \

#augustus  --species=maize \
# /lustre/groups/bioservices/secure/syngenta/working/rob/cosmid/HF050.fna \
#--outfile=HF050-aug.txt \
#--genemodel=partial \
#--singlestrand=true \
#--protein=on \
#--introns=on \
#--start=on \
#--stop=on \
#--cds=on \
#--UTR=off \
#--codingseq=on \
#--gff3=on \
#--noInFrameStop=true

augustus  --species=maize \
 /lustre/groups/bioservices/secure/syngenta/working/rob/cosmid/HF051.fna \
--outfile=HF051-aug.txt \
--genemodel=partial \
--singlestrand=true \
--protein=on \
--introns=on \
--start=on \
--stop=on \
--cds=on \
--UTR=off \
--codingseq=on \
--gff3=on \
--noInFrameStop=true

echo "FIN"


