#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=196:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=1

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
##PBS -l pmem=7600mb
#PBS -l vmem=79gb
#PBS -N synfillterr
##PBS -q bigiron
#export TMPDIR=$HOME/tmp

#Number of times to run this script
##PBS -t 1-12


cd ~/syn/sept2015
umask 007
set -eu
#file=$(sed -n -e "${PBS_ARRAYID}p" files.txt)

#echo   ${file};


#cut adapter
~/sw/cutadapt/cutadapt-1.4.1/bin/cutadapt -b AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC -O 5 -f fastq --quality-base=64 all3FlashedFiles.fastq > allFlashed-cutadapt.fastq

echo "finished job"

#mv ${file}.fastq.adapt.dup ${file}/

