#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=168:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=12

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=88gb

#PBS -N gggeneSimmons
#PBS -q bigiron
##PBS -t 1-5
umask 007
set -eu

#ssid=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/bioservices/hockeypuck/old/blueberry/reads/hiseq/file.txt)
#dir=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/bioservices/p2ep/dhmri/run2-oat-brass-oct25-2013/filedir.txt)

echo "Launching fastx"

#cd $home

cd /lustre/groups/bioservices/secure/syngenta/working/rob/cosmid/genemark/ 

module load genemarks/2.5m

#gmsn.pl --gm --name brass -est ../../ncbi-est-brass.fna

#gm -m /lustre/groups/p2ep/strawberry/annot/genmark/straw_gm.mat -v ../HF050.fna
gm -m /lustre/groups/p2ep/strawberry/annot/genmark/straw_gm.mat -v ../HF051.fna



echo "FIN"


