#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=168:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=12

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=88gb

#PBS -N ggggth-straw
#PBS -q bigiron
##PBS -t 1-5
umask 007
set -eu

#ssid=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/bioservices/hockeypuck/old/blueberry/reads/hiseq/file.txt)
#dir=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/bioservices/p2ep/dhmri/run2-oat-brass-oct25-2013/filedir.txt)

echo "Launching fastx"

#cd $home
#module load augustus
#module load blat

cd /lustre/groups/p2ep/strawberry/annot/genomethreader/


~/sw/genomethreader/gth-1.6.2-Linux_x86_64-64bit/bin/gth \
-gff3out \
-maskpolyatails \
-intermediate \
-paralogs \
-species medicago \
-protein /lustre/groups/p2ep/strawberry/fromGDR/ncbi-peptides-fvesca.faa \
-cdna /lustre/groups/p2ep/strawberry/fromGDR/ncbi-ests-fvesca.fna \
-genomic /lustre/groups/p2ep/strawberry/fromGDR/fvesca_v1.1_FC-all.fna \


echo "FIN"


