#!/bin/bash
#PBS -N flanBakedat400
#PBS -l nodes=1:ppn=12
#PBS -l walltime=96:00:00
#PBS -l vmem=95g
#PBS -t 1-3

cd $PBS_O_WORKDIR

export PATH=/lustre/home/lheater/sw/metaphlan/1.7.6/metaphlan:$PATH

module load metaphlan
module load bowtie2

#FILE=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/bioservices/secure/syngenta/working/rob/project2/flashmerged/file-ext.txt)
FILE=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/bioservices/secure/syngenta/working/rob/project2/flashmerged/file-notco.txt)
#metaphlan.py --bowtie2out /lustre/home/lheater/syn/meta/$FILE.out.vs.txt -o /lustre/home/lheater/syn/meta/$FILE.s.mtphln.vs.txt --input_type automatic --bowtie2db /lustre/home/lheater/sw/metaphlan/1.7.6/metaphlan/bowtie2db/mpa --nproc 12 -t 'reads_map' --tax_lev 's' /lustre/home/lheater/bin/$FILE

ANALYSIS=reads_map

#~/sw/metaphlan/metaphlan.py --bowtie2out /lustre/groups/bioservices/secure/syngenta/working/rob/project2/metaphlan/$FILE.bt2.txt -o /lustre/groups/bioservices/secure/syngenta/working/rob/project2/metaphlan/${FILE}-genus.mtphln.${ANALYSIS}.txt --input_type automatic --bowtie2db /lustre/home/rreid2/sw/metaphlan/bowtie2db/mpa --bt2_ps sensitive --nproc 12 -t 'reads_map' --tax_lev 'g' /lustre/groups/bioservices/secure/syngenta/working/rob/project2/flashmerged/$FILE.fna

#~/sw/metaphlan/metaphlan.py --bowtie2out /lustre/groups/bioservices/secure/syngenta/working/rob/project2/metaphlan/$FILE.bt2.txt -o /lustre/groups/bioservices/secure/syngenta/working/rob/project2/metaphlan/${FILE}-genus.mtphln.${ANALYSIS}.txt --input_type automatic --bowtie2db /lustre/home/rreid2/sw/metaphlan/bowtie2db/mpa --bt2_ps sensitive --nproc 12 -t 'reads_map' --tax_lev 'g' /lustre/groups/bioservices/secure/syngenta/working/rob/project2/flashmerged/$FILE.fastq

~/sw/metaphlan/metaphlan.py --input_type bowtie2out /lustre/groups/bioservices/secure/syngenta/working/rob/project2/metaphlan/$FILE.bt2.txt -o /lustre/groups/bioservices/secure/syngenta/working/rob/project2/metaphlan/$FILE-phylum.mtphln.${ANALYSIS}.txt --nproc 12 -t 'reads_map' --tax_lev 'p'

#nANALYSIS=rel_ab

# ~/sw/metaphlan/metaphlan.py --input_type bowtie2out /lustre/home/rreid2/syn/metaphlan/$FILE.bt2.txt -o /lustre/home/rreid2/syn/metaphlan/$FILE-order.mtphln.${ANALYSIS}.txt --nproc 12 -t 'rel_ab' --tax_lev 'o' 

#####  Testing bowtie sensitvity   ######

#~/sw/metaphlan/metaphlan.py --bowtie2out /lustre/home/rreid2/syn/metaphlan/$FILE.bt2-vsensLocal.txt -o /lustre/home/rreid2/syn/metaphlan/$FILE-species.mtphln.${ANALYSIS}-vsenslocal.txt --input_type automatic --bowtie2db /lustre/home/rreid2/sw/metaphlan/bowtie2db/mpa --bt2_ps very-sensitive-local --nproc 12 -t 'rel_ab' --tax_lev 's' /lustre/home/rreid2/syn/concat_filtered//$FILE


#~/sw/metaphlan/metaphlan.py --input_type bowtie2out /lustre/home/rreid2/syn/metaphlan/$FILE.bt2.txt -o /lustre/home/rreid2/syn/metaphlan/$FILE-all.mtphln.${ANALYSIS}.txt --nproc 12 -t 'reads_map' --tax_lev 'a'

#~/sw/metaphlan/metaphlan.py --input_type bowtie2out /lustre/home/rreid2/syn/metaphlan/$FILE.bt2.txt -o /lustre/home/rreid2/syn/metaphlan/$FILE-all.mtphln.${ANALYSIS}.txt --nproc 12 -t 'rel_ab' --tax_lev 'a'

#~/sw/metaphlan/metaphlan.py --input_type bowtie2out /lustre/groups/bioservices/secure/syngenta/working/rob/project2/metaphlan/$FILE.bt2.txt -o /lustre/groups/bioservices/secure/syngenta/working/rob/project2/metaphlan/$FILE-class.mtphln.${ANALYSIS}.txt --nproc 12 -t 'reads_map' --tax_lev 'c'
  
#~/sw/metaphlan/metaphlan.py --input_type bowtie2out /lustre/home/rreid2/syn/metaphlan/$FILE.bt2.txt -o /lustre/home/rreid2/syn/metaphlan/$FILE-class.mtphln.${ANALYSIS}.txt --nproc 12 -t 'rel_ab' --tax_lev 'c'

 #~/sw/metaphlan/metaphlan.py --input_type bowtie2out /lustre/home/rreid2/syn/metaphlan/$FILE.bt2.txt -o /lustre/home/rreid2/syn/metaphlan/$FILE-phylum.mtphln.${ANALYSIS}.txt --nproc 12 -t 'reads_map' --tax_lev 'p'
 
#~/sw/metaphlan/metaphlan.py --input_type bowtie2out /lustre/home/rreid2/syn/metaphlan/$FILE.bt2.txt -o /lustre/home/rreid2/syn/metaphlan/$FILE-phylum.mtphln.${ANALYSIS}.txt --nproc 12 -t 'rel_ab' --tax_lev 'p'

