#!/bin/sh

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=98:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=2

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)


#PBS -N SeqcleanChloro
#PBS -q bigiron

##home=/gpfs/fs3/home/rreid2


# launching Launching build_lmer_table on a single node so it can run till the cows come home
#echo "Launching Repeat Masker"
export PATH=$HOME/bin:$PATH

cd $HOME/blueberry/reads/454Sequences/all/  


for file in $(find ./ -name "*.cln");
do
        echo   ${file};
	  /gpfs/fs3/home/rreid2/bin/seqclean/cln2qual ${file} ${file%fasta.cln}"qual"

done


