#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=168:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=2

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=36gb
#PBS -j oe
#PBS -N fffilterVCF-banana
#PBS -q copperhead
##PBS -t 1-20
umask 007
set -eu

#file=$(sed -n -e "${PBS_ARRAYID}p" /scratch/rreid2/banana/filter/trimgalore/file.txt)
#dir=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/lorainelab/data/illumina/sweet_potato/filtered/dir.txt)

echo "Launching BWA alignment"

#module load java8 
#module load samtools
#module load bwa
#module load bcftools


cd /nobackup/banana_genome/filterbyDP

python /users/rreid2/scripts/python/filterVCF-byRepeat-banana.py noplantain-byDP-byGeneLocation-v2.vcf  /scratch/rreid2/banana/repeat/red/repeatdir/justchr-repeats.txt









