#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=468:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=32

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=488gb
#PBS -j oe
#PBS -N ssspades-run3
#PBS -q hammerhead
#PBS -t 1-20
umask 007
set -eu

file=$(sed -n -e "${PBS_ARRAYID}p" /scratch/rreid2/banana/filter/trimgalore/file.txt)
#dir=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/lorainelab/data/illumina/sweet_potato/filtered/dir.txt)

echo "Launching BWA alignment"

#module load java8 
module load spades

cd /scratch/rreid2/banana/denovo/spades

spades.py -1 /scratch/rreid2/banana/filter/trimmomatic/trimgalored/output_${file}-R1_paired.fq \
-2 /scratch/rreid2/banana/filter/trimmomatic/trimgalored/output_${file}-R2_paired.fq \
--careful \
--disable-gzip-output \
-t 32 \
-m 888 \
-k 21,33,55,77 \
-o ./${file}





