#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=568:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=64

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=1988gb
#PBS -j oe
#PBS -N ssspades-mchare
#PBS -q hammerhead
##PBS -t 1-20
umask 007
set -eu

#file=$(sed -n -e "${PBS_ARRAYID}p" /scratch/rreid2/banana/filter/trimgalore/file.txt)
#dir=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/lorainelab/data/illumina/sweet_potato/filtered/dir.txt)

echo "Launching BWA alignment"

#module load java8 
module load spades

cd /scratch/rreid2/banana/denovo/spades

spades.py --pe1-1 /scratch/rreid2/banana/filter/trimmomatic/trimgalored/output_1468_S3_L001-R1_paired.fq \
--pe1-2 /scratch/rreid2/banana/filter/trimmomatic/trimgalored/output_1468_S3_L001-R2_paired.fq \
--pe2-1 /scratch/rreid2/banana/filter/trimmomatic/trimgalored/output_281_S6_L002-R1_paired.fq \
--pe2-2 /scratch/rreid2/banana/filter/trimmomatic/trimgalored/output_281_S6_L002-R2_paired.fq \
--pe3-1 /scratch/rreid2/banana/filter/trimmomatic/trimgalored/output_1466_S2_L001-R1_paired.fq \
--pe3-2 /scratch/rreid2/banana/filter/trimmomatic/trimgalored/output_1466_S2_L001-R2_paired.fq \
--careful \
--disable-gzip-output \
-t 64 \
-m 1988 \
-k 21,33,55 \
-o ./mchare 




