#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=168:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=1

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=7550mb

#PBS -N iiinterpro-4greg

#Number of times to run this script
#PBS -t 1-902

set -eu
umask 007

file=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/janieslab/interpro/forgreg/file.txt)

cd /lustre/groups/janieslab/interpro/forgreg

~/sw/interproscan-5.7-48.0/interproscan.sh -i ${file} -o ${file}-iprscan.out  -goterms -iprlookup -seqtype p -pa -appl Panther-9.0,PfamA-27.0,PrositeProfiles-20.97 -f tsv

echo " All finished"
