#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=68:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=6

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l vmem=40GB

#PBS -N EverbbbblastingLove 
#PBS -q copperhead


#Number of times to run this script
##PBS -t 1-12
##PBS -l pmem=7600mb

set eu
umask 007

#file=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/p2ep/brassica/blast/file.txt)

cd /nobackup/oat_genome/clay/ 
module load blast/2.3.0+ 



makeblastdb -in /nobackup/oat_genome/canu/oat.steelhead/oat5.contigs.fasta    -dbtype nucl

blastn -db /nobackup/oat_genome/canu/oat.steelhead/oat5.contigs.fasta -out ./blastn-clayVSoat5.txt -query ./claymarkers.fna \
-num_threads 6 -dust no -word_size 16 -task megablast -evalue 1e-08 -outfmt 6


