#!/bin/bash
#PBS -l walltime=696:00:00  # Maximum amount of real time for the job to run in HH:MM:SS
#PBS -l nodes=1:ppn=64     # Number of nodes and processors per node requested by job
#PBS -l mem=3800GB           # Maximum physical memory to use for jobi
#PBS -N ffflye-canu          # User-defined name for job
#PBS -j oe                # Write STDERR to STDOUT output file
#PBS -q hammerhead        # Job queue to submit this script to

# User prologue.  Must be owned by user, not writable by group or other
##PBS -l prologue=/projects/oat_genome/scripts/prologue.sh
# User epilogue.  Must be owned by user, not writable by group or other
##PBS -l epilogue=/projects/oat_genome/scripts/epilogue.sh

IFS=$'\n'          # Internal Field Separator is newline
set -eu            # e - Exit on error
                   # u - Undefined variable is an error
                   # x - enable trace (print commands before running)
umask 007          # user  - all permissions
                   # group - all permissions
                   # other - no permissions
shopt -s nullglob  # Treat empty glob (*) as nothing instead of empty string

#module list
echo "WTF"

cd /nobackup/oat_genome/flye

/nobackup/oat_genome/sw/Flye/bin/flye --pacbio-corr /nobackup/oat_genome/canu/oat6/oat6.correctedReads.fasta.gz \
--threads 64 \
--min-overlap 2000 \
--out-dir 1-flye \
--genome-size 13g

#--subassemblies /nobackup/oat_genome/canu/oat.steelhead/oat5.contigs.fasta \


#/users/rreid2/sw/smartdenovo/smartdenovo/smartdenovo.pl /nobackup/oat_genome/canu/oat6/oat6.correctedReads.fasta.gz  > oat6-corrected.mak 

#make -f oat6-corrected.mak 



