#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=568:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=8

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l mem=488gb
#PBS -j oe
#PBS -N rrrope2bwt
#PBS -q hammerhead
#PBS -t 1-18
umask 007
set -eu

file=$(sed -n -e "${PBS_ARRAYID}p" /nobackup/oat_genome/illumina/file.txt)
#dir=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/lorainelab/data/illumina/sweet_potato/filtered/dir.txt)

echo "Launching BWT transform."

#module load java8 
#module load meraculous

cd /nobackup/oat_genome/fmlrc

/nobackup/oat_genome/sw/ropebwt2/ropebwt2-master/ropebwt2 \
 -o ${file}.bwt \
 -i  /nobackup/oat_genome/illumina/${file}






