#!/bin/bash
#PBS -l walltime=1:00:00  # Maximum amount of real time for the job to run in HH:MM:SS
#PBS -l nodes=1:ppn=8     # Number of nodes and processors per node requested by job
#PBS -l mem=60GB           # Maximum physical memory to use for job
#PBS -N sssmrt-denovo-test          # User-defined name for job
#PBS -j oe                # Write STDERR to STDOUT output file
#PBS -q copperhead        # Job queue to submit this script to

# User prologue.  Must be owned by user, not writable by group or other
##PBS -l prologue=/projects/oat_genome/scripts/prologue.sh
# User epilogue.  Must be owned by user, not writable by group or other
##PBS -l epilogue=/projects/oat_genome/scripts/epilogue.sh

IFS=$'\n'          # Internal Field Separator is newline
set -eu            # e - Exit on error
                   # u - Undefined variable is an error
                   # x - enable trace (print commands before running)
umask 007          # user  - all permissions
                   # group - all permissions
                   # other - no permissions
shopt -s nullglob  # Treat empty glob (*) as nothing instead of empty string

#module list
echo "WTF"

cd ~/sw/smartdenovo

make -f wtasm.mak



