#!/bin/sh

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=96:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=1

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
##PBS -l pmem=7600mb
#PBS -l vmem=200gb
#PBS -N dupydupy
#PBS -q bigiron
export TMPDIR=$HOME/tmp

#Number of times to run this script
##PBS -t 1-3

##home=/gpfs/fs3/home/rreid2


# launching Launching build_lmer_table on a single node so it can run till the cows come home
#echo "Launching Repeat Masker"
#source /sw/functions.sh
#prepend_dir PATH $HOME/bin
#prepend_dir PATH $HOME/scripts
#prepend_dir PATH $HOME/bin/RepeatMasker

#export PATH=$HOME/bin:$PATH


cd /lustre/groups/bioservices/boneym

#file=$(sed -n -e "${PBS_ARRAYID}p" ./allfiles.txt)

#for file in $(find ./ -name "*.fastq");
#do
 #       echo   ${file};

 

##
##          Cutadapt removes adapter
##
##	    dynatrim removes poor quality dynamically
##

 
 #perl ./dynatrim.pl -h 20 metal.fastq
file="metal"

#cut adapter
~/sw/cutadapt-1.0/cutadapt -a GATCGGAAGAGCGGT $file.fastq > $file.fastq.adapt

#dynamically trim
perl dynatrim.pl -h 20 $file.fastq.adapt



echo "finished dup job"
#done

#perl ./trimRobsTweak.pl ./data/June_22nd_2011_Run/js1.fastq -h 0


