#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=468:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=8

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
#PBS -l mem=48gb
#PBS -j oe
#PBS -N gggatk-mayote
#PBS -q steelhead
#PBS -t 1-19
umask 007
set -eu

file=$(sed -n -e "${PBS_ARRAYID}p" /nobackup/rogers_research/rob/mayotte/files.txt)
#dir=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/lorainelab/data/illumina/sweet_potato/filtered/dir.txt)

echo "Launching GATK haplotyper"

#module load java8 
#module load samtools
#module load bwa
#module load bcftools
module load gatk

cd /nobackup//rogers_research/rob/mayotte/gatk2

java -jar /apps/pkg/gatk-3.8/GenomeAnalysisTK.jar \
 --analysis_type HaplotypeCaller \
 -R /nobackup/rogers_research/rob/gatk/nick-gatk/dyak.ref.fna \
 -I /nobackup/rogers_research/rob/mayotte/picard/readgrouped-${file}.bam  \
 -o ${file}-gatk.vcf \
 --emitRefConfidence BP_RESOLUTION \
 --min_base_quality_score 15 \
 -nct 8
 #-stand_call_conf 50 \
 #-ploidy 40 \
 #--min_base_quality_score 15 \
 #-nct 64 
 #--select_expressions "AF>0.1"




