perl PE_FIX_POSTQC.pl --pe1 oat10C_R1_trimmed_clipped.fastq --pe2 oat10C_R2_trimmed_clipped.fastq
perl PE_FIX_POSTQC.pl --pe1 oat118C_R1_trimmed_clipped.fastq --pe2 oat118C_R2_trimmed_clipped.fastq
perl PE_FIX_POSTQC.pl --pe1 oat128N-H_R1_trimmed_clipped.fastq --pe2 oat128N-H_R2_trimmed_clipped.fastq
perl PE_FIX_POSTQC.pl --pe1 oat141N_R1_trimmed_clipped.fastq --pe2 oat141N_R2_trimmed_clipped.fastq
perl PE_FIX_POSTQC.pl --pe1 oat171N-H_R1_trimmed_clipped.fastq --pe2 oat171N-H_R2_trimmed_clipped.fastq
perl PE_FIX_POSTQC.pl --pe1 oat1757_R1_trimmed_clipped.fastq --pe2 oat1757_R2_trimmed_clipped.fastq
perl PE_FIX_POSTQC.pl --pe1 oat1760_R1_trimmed_clipped.fastq --pe2 oat1760_R2_trimmed_clipped.fastq
perl PE_FIX_POSTQC.pl --pe1 oat1762_R1_trimmed_clipped.fastq --pe2 oat1762_R2_trimmed_clipped.fastq
perl PE_FIX_POSTQC.pl --pe1 oat1763_R1_trimmed_clipped.fastq --pe2 oat1763_R2_trimmed_clipped.fastq
perl PE_FIX_POSTQC.pl --pe1 oat1764_R1_trimmed_clipped.fastq --pe2 oat1764_R2_trimmed_clipped.fastq
perl PE_FIX_POSTQC.pl --pe1 oat187C_R1_trimmed_clipped.fastq --pe2 oat187C_R2_trimmed_clipped.fastq
perl PE_FIX_POSTQC.pl --pe1 oat196C_R1_trimmed_clipped.fastq --pe2 oat196C_R2_trimmed_clipped.fastq
perl PE_FIX_POSTQC.pl --pe1 oat200C_R1_trimmed_clipped.fastq --pe2 oat200C_R2_trimmed_clipped.fastq
perl PE_FIX_POSTQC.pl --pe1 oat30C_R1_trimmed_clipped.fastq --pe2 oat30C_R2_trimmed_clipped.fastq
perl PE_FIX_POSTQC.pl --pe1 oat31N_R1_trimmed_clipped.fastq --pe2 oat31N_R2_trimmed_clipped.fastq
perl PE_FIX_POSTQC.pl --pe1 oat33N_R1_trimmed_clipped.fastq --pe2 oat33N_R2_trimmed_clipped.fastq
perl PE_FIX_POSTQC.pl --pe1 oat34N_R1_trimmed_clipped.fastq --pe2 oat34N_R2_trimmed_clipped.fastq
perl PE_FIX_POSTQC.pl --pe1 oat65N_R1_trimmed_clipped.fastq --pe2 oat65N_R2_trimmed_clipped.fastq
perl PE_FIX_POSTQC.pl --pe1 oat74C_R1_trimmed_clipped.fastq --pe2 oat74C_R2_trimmed_clipped.fastq
perl PE_FIX_POSTQC.pl --pe1 oat78C_R1_trimmed_clipped.fastq --pe2 oat78C_R2_trimmed_clipped.fastq
perl PE_FIX_POSTQC.pl --pe1 oat88N_R1_trimmed_clipped.fastq --pe2 oat88N_R2_trimmed_clipped.fastq
