#!/bin/sh

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=96:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=1

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
##PBS -l pmem=7600mb
#PBS -l vmem=79gb
#PBS -N coldCutsyummm
##PBS -q bigiron
#export TMPDIR=$HOME/tmp

#Number of times to run this script
#PBS -t 1-24

##home=/gpfs/fs3/home/rreid2



cd /lustre/groups/bioservices/kohlmeier/rawReads/dup

#ssid=$(sed -n -e "${PBS_ARRAYID}p" ~/echinoderms/dl/120727B2/files.txt)
file=$(sed -n -e "${PBS_ARRAYID}p" files.txt)

#for file in $(find ./ -name "*.fastq");
#do
 #       echo   ${file};

#cut adapter
~/sw/cutadapt-1.0/cutadapt -a GATCGGAAGAGCGGT ${file} > ${file}.adapt

#dynamically trim
#perl ~/scripts/perl/dynatrim.pl -h 20 ${file}
perl ~/scripts/perl/trimdup.pl -h 0 ${file}.adapt
#perl ~/old/scripts/perl/raadTrim.pl -h 20 ${file}.adapt

echo "finished dup job"
#done



