#!/bin/bash

# Request a run time of 5 hours and 30 minutes
#PBS -l walltime=96:30:00

# Request 1 processor in 1 node
#PBS -l nodes=1:ppn=1

# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)
##PBS -l pmem=7600mb
#PBS -l vmem=79gb
#PBS -N coldCutsyummm
##PBS -q bigiron
#export TMPDIR=$HOME/tmp

#Number of times to run this script
#PBS -t 1-28

##home=/gpfs/fs3/home/rreid2

file=$(sed -n -e "${PBS_ARRAYID}p" /lustre/groups/bioservices/secure/kohlmeier/5kregion/filtered/files.txt)

cd /lustre/groups/bioservices/secure/kohlmeier/5kregion/filtered/

#ssid=$(sed -n -e "${PBS_ARRAYID}p" ~/echinoderms/dl/120727B2/files.txt)
#file=$(sed -n -e "${PBS_ARRAYID}p" files.txt)

#for fastq in *.fastq.gz
#do
        echo   ${file};

#	gunzip "$fastq"

#done

#cp *.fastq ../filtered




#cut adapter
~/sw/cutadapt-1.0/cutadapt -a GATCGGAAGAGCGGT ${file} > ${file}.adapt

#dynamically trim
perl ~/scripts/perl/dynatrim.pl -h 20 ${file}.adapt 
#perl ~/scripts/perl/dynatrim.pl -h 20 UNC_Kohlmeier_130410_Run_Sample_${file}__Amplicon_GTTTCG_L003_R2_001.fastq

#perl ~/scripts/perl/trimdup.pl -h 0 UNC_Kohlmeier_130410_Run_Sample_${file}__Amplicon_GTTTCG_L003_R1_001.fastq.adapt
#perl ~/scripts/perl/trimdup.pl -h 0 UNC_Kohlmeier_130410_Run_Sample_${file}__Amplicon_GTTTCG_L003_R2_001.fastq.adapt
#perl ~/old/scripts/perl/raadTrim.pl -h 20 ${file}.adapt

echo "finished dup job"
#done



